# Generated by Django 5.2.7 on 2025-12-07 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionCuotaLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=32)),
                ('fecha', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_notificaciones_cuotas', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Log de notificación de cuotas',
                'verbose_name_plural': 'Logs de notificaciones de cuotas',
                'unique_together': {('cliente', 'numero', 'fecha')},
            },
        ),
    ]
