# Generated by Django 5.2.7 on 2025-12-07 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvioRecordatoriosCuotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('oficina', models.CharField(help_text="ID lógico de la oficina (por ejemplo: '1', '2', '3').", max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Envío de recordatorios de cuotas',
                'verbose_name_plural': 'Envíos de recordatorios de cuotas',
                'unique_together': {('fecha', 'oficina')},
            },
        ),
    ]
