# Generated by Django 5.2.7 on 2025-12-07 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('notificaciones', '0002_enviorecordatorioscuotas'),
        ('polizas', '0008_cuponrobo_monto'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvioRecordatorioDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oficina', models.CharField(blank=True, help_text='ID lógico de la oficina desde donde se envió.', max_length=16, null=True)),
                ('telefono', models.CharField(help_text='Número de WhatsApp al que se envió el mensaje.', max_length=32)),
                ('monto_total', models.DecimalField(decimal_places=2, default=0, help_text='Suma de los importes de las cuotas incluidas en el mensaje.', max_digits=12)),
                ('cuotas_ids', models.JSONField(blank=True, default=list, help_text='Lista de IDs de cuotas incluidas en el mensaje.')),
                ('texto_resumen', models.CharField(blank=True, help_text="Resumen corto: ej. '3 cuotas, total $45.000'.", max_length=255)),
                ('estado_envio', models.CharField(default='OK', help_text="Estado del envío: p.ej. 'OK' o 'ERROR'.", max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_recordatorios_cuotas', to='clientes.cliente')),
                ('envio', models.ForeignKey(blank=True, help_text='Ejecución (día + oficina) asociada al envío.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='notificaciones.enviorecordatorioscuotas')),
                ('poliza_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_recordatorios_cuotas', to='polizas.poliza')),
            ],
            options={
                'verbose_name': 'Detalle de envío de recordatorio',
                'verbose_name_plural': 'Detalles de envíos de recordatorios',
                'ordering': ['-created_at'],
            },
        ),
    ]
