# Generated by Django 5.2.7 on 2025-10-22 04:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polizas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuota_nro', models.IntegerField(db_index=True)),
                ('fecha_vencimiento', models.DateField(db_index=True)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('pagado', models.BooleanField(db_index=True, default=False)),
                ('forma_pago', models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia')], max_length=20, null=True)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('poliza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='polizas.poliza')),
            ],
            options={
                'ordering': ['poliza_id', 'cuota_nro'],
            },
        ),
        migrations.CreateModel(
            name='AlertaEnviada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('3_antes', '3 días antes'), ('hoy', 'Día de vencimiento'), ('3_despues', '3 días después'), ('7_despues', '7 días después'), ('30_despues', '30 días después')], max_length=50)),
                ('enviada', models.BooleanField(default=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='pagos.cuota')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='MedioCobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(choices=[('mercado_pago', 'Mercado Pago'), ('grubank', 'Grubank'), ('astropay', 'AstroPay'), ('uala', 'Ualá'), ('banco', 'Banco'), ('otro', 'Otro')], db_index=True, default='mercado_pago', max_length=20)),
                ('tipo', models.CharField(choices=[('alias', 'Alias'), ('cbu', 'CBU'), ('cvu', 'CVU'), ('link', 'Link de pago')], db_index=True, default='alias', max_length=10)),
                ('valor', models.CharField(help_text='Alias/CBU/CVU o URL del link de pago', max_length=150, unique=True)),
                ('titular_nombre', models.CharField(help_text='Nombre a mostrar al cliente (titular de la cuenta)', max_length=120)),
                ('etiqueta', models.CharField(blank=True, default='', help_text="Etiqueta interna, ej: 'MP Manu'", max_length=100)),
                ('qr_url', models.URLField(blank=True, default='', help_text='URL del QR (si aplica)')),
                ('notas', models.TextField(blank=True, default='')),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('ultimo_uso', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('usos_totales', models.PositiveIntegerField(default=0)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-activo', 'ultimo_uso', 'id'],
                'indexes': [models.Index(fields=['activo', 'ultimo_uso'], name='pagos_medio_activo_e2648f_idx'), models.Index(fields=['proveedor', 'tipo'], name='pagos_medio_proveed_0dc32d_idx')],
                'constraints': [models.UniqueConstraint(fields=('proveedor', 'tipo', 'valor'), name='medio_cobro_unico_por_proveedor_tipo_valor')],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('metodo', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('mercado_pago', 'Mercado Pago'), ('tarjeta', 'Tarjeta')], max_length=50)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('cuota_nro', models.IntegerField(db_index=True)),
                ('registrado_en_balance', models.BooleanField(default=False)),
                ('cuota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='pagos.cuota')),
                ('poliza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='polizas.poliza')),
            ],
            options={
                'ordering': ['-fecha', 'poliza_id', 'cuota_nro'],
            },
        ),
        migrations.AddIndex(
            model_name='cuota',
            index=models.Index(fields=['poliza', 'cuota_nro'], name='pagos_cuota_poliza__8d6dee_idx'),
        ),
        migrations.AddIndex(
            model_name='cuota',
            index=models.Index(fields=['pagado', 'fecha_vencimiento'], name='pagos_cuota_pagado_baf126_idx'),
        ),
        migrations.AddConstraint(
            model_name='cuota',
            constraint=models.CheckConstraint(condition=models.Q(('pagado', False), ('fecha_pago__isnull', False), _connector='OR'), name='cuota_pagada_requiere_fecha_pago'),
        ),
        migrations.AlterUniqueTogether(
            name='cuota',
            unique_together={('poliza', 'cuota_nro')},
        ),
        migrations.AddIndex(
            model_name='alertaenviada',
            index=models.Index(fields=['tipo'], name='pagos_alert_tipo_45c117_idx'),
        ),
        migrations.AddIndex(
            model_name='alertaenviada',
            index=models.Index(fields=['fecha'], name='pagos_alert_fecha_3c0843_idx'),
        ),
        migrations.AddIndex(
            model_name='alertaenviada',
            index=models.Index(fields=['cuota', 'tipo'], name='pagos_alert_cuota_i_ecca6e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='alertaenviada',
            unique_together={('cuota', 'tipo')},
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['poliza', 'cuota_nro'], name='pagos_pago_poliza__382f8e_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['fecha'], name='pagos_pago_fecha_f7902d_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['registrado_en_balance'], name='pagos_pago_registr_26cf23_idx'),
        ),
    ]
