# Generated by Django 5.2.7 on 2025-11-05 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediocobro',
            name='proveedor',
            field=models.CharField(choices=[('mercado_pago', 'Mercado Pago'), ('billetera_virtual', 'Billetera Virtual'), ('grubank', 'Grubank'), ('astropay', 'AstroPay'), ('uala', 'Ualá'), ('banco', 'Banco'), ('otro', 'Otro')], db_index=True, default='mercado_pago', max_length=20),
        ),
        migrations.AlterField(
            model_name='mediocobro',
            name='titular_nombre',
            field=models.CharField(blank=True, default='', help_text='Nombre a mostrar al cliente (titular de la cuenta)', max_length=120),
        ),
    ]
