# Generated by Django 5.2.7 on 2026-02-11 04:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0003_alter_pago_metodo'),
        ('polizas', '0009_rename_foto_public_id_cuponrobo_foto_perfil_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='actualizado',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['creado'], name='pagos_pago_creado_103057_idx'),
        ),
    ]
