# Generated by Django 5.2.7 on 2026-02-11 04:26

import django.utils.timezone
from django.db import migrations, models


def backfill_pago_registrado_en(apps, schema_editor):
    Pago = apps.get_model("pagos", "Pago")
    now = django.utils.timezone.now()

    # Seteamos registrado_en para filas existentes:
    # prioridad: creado -> actualizado -> now
    for p in Pago.objects.filter(registrado_en__isnull=True).only("id", "creado", "actualizado").iterator(chunk_size=2000):
        ts = getattr(p, "creado", None) or getattr(p, "actualizado", None) or now
        Pago.objects.filter(id=p.id, registrado_en__isnull=True).update(registrado_en=ts)


class Migration(migrations.Migration):

    dependencies = [
        ("pagos", "0004_pago_actualizado_pago_creado_and_more"),
        ("polizas", "0009_rename_foto_public_id_cuponrobo_foto_perfil_public_id"),
    ]

    operations = [
        # 1) Agregar nullable (sin default) para que SQLite no reviente al recrear la tabla
        migrations.AddField(
            model_name="pago",
            name="registrado_en",
            field=models.DateTimeField(null=True, blank=True, db_index=True),
        ),

        # 2) Backfill con data existente
        migrations.RunPython(backfill_pago_registrado_en, migrations.RunPython.noop),

        # 3) Dejar NOT NULL + auto_now_add (sin default)
        migrations.AlterField(
            model_name="pago",
            name="registrado_en",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),

        migrations.AddIndex(
            model_name="pago",
            index=models.Index(fields=["registrado_en"], name="pagos_pago_registr_2ffaba_idx"),
        ),
    ]
