# Generated by Django 5.2.7 on 2026-02-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0005_pago_registrado_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuota',
            name='observaciones_pago',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cuota',
            name='ultima_observacion_pago',
            field=models.TextField(blank=True, null=True),
        ),
    ]
