# Generated by Django 5.2.7 on 2026-02-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0006_cuota_observaciones_pago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuota',
            name='observaciones_pago',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='ultima_observacion_pago',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='mediocobro',
            name='etiqueta',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='mediocobro',
            name='qr_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='mediocobro',
            name='titular_nombre',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
