# Generated by Django 5.2.7 on 2026-03-02 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0007_alter_cuota_observaciones_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuota',
            name='pago_registrado_en',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
