# Generated by Django 5.2.7 on 2026-03-15 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0008_cuota_pago_registrado_en'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='mediocobro',
            name='medio_cobro_unico_por_proveedor_tipo_valor',
        ),
        migrations.AddField(
            model_name='mediocobro',
            name='oficina',
            field=models.CharField(blank=True, db_index=True, help_text="Sucursal dueña de este alias (ej: '1', '2', '3').", max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='mediocobro',
            name='valor',
            field=models.CharField(help_text='Alias/CBU/CVU o URL del link de pago', max_length=150),
        ),
        migrations.AddIndex(
            model_name='mediocobro',
            index=models.Index(fields=['oficina'], name='pagos_medio_oficina_dd68a3_idx'),
        ),
        migrations.AddConstraint(
            model_name='mediocobro',
            constraint=models.UniqueConstraint(fields=('proveedor', 'tipo', 'valor', 'oficina'), name='medio_cobro_unico_por_proveedor_tipo_valor_oficina'),
        ),
    ]
