# Generated by Django 5.2.7 on 2026-04-26 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0009_remove_mediocobro_medio_cobro_unico_por_proveedor_tipo_valor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertaenviada',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
