# Generated by Django 5.2.7 on 2026-05-21 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0010_alter_alertaenviada_fecha'),
        ('polizas', '0018_poliza_es_renovacion_poliza_poliza_origen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='estado_verificacion',
            field=models.CharField(choices=[('pendiente', 'Pendiente de verificar'), ('verificado', 'Verificado · todo OK'), ('falta_emitir', 'Atención · Falta emitir en compañía'), ('pago_post_baja', 'Atención · Pagó después de baja'), ('avisar_vendedor', 'Atención · Avisar al vendedor'), ('revisar_mariano', 'Atención · Revisar con Mariano')], db_index=True, default='pendiente', max_length=30),
        ),
        migrations.AddField(
            model_name='pago',
            name='verificacion_nota',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='verificado_en',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='verificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_verificados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['estado_verificacion'], name='pagos_pago_estado__02cf98_idx'),
        ),
    ]
