# Generated by Django 5.2.7 on 2026-07-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0011_pago_estado_verificacion_pago_verificacion_nota_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='cuit_remitente',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='pago',
            name='destino_cuenta',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='pago',
            name='enviado_por',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='pago',
            name='nro_operacion',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
