# Generated by Django 5.2.7 on 2026-07-08 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0012_pago_cuit_remitente_pago_destino_cuenta_and_more'),
        ('solicitudes', '0007_rename_solicitudes_oficina_e12ff6_idx_solicitudes_oficina_8e1f93_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuota',
            name='responsable_empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuotas_cobradas', to='solicitudes.empleado'),
        ),
        migrations.AddField(
            model_name='cuota',
            name='responsable_nombre',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='pago',
            name='responsable_empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_cobrados', to='solicitudes.empleado'),
        ),
        migrations.AddField(
            model_name='pago',
            name='responsable_nombre',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
