# Generated by Django 5.2.7 on 2026-07-16 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0013_cuota_responsable_empleado_cuota_responsable_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='estado_verificacion',
            field=models.CharField(choices=[('pendiente', 'Pendiente de verificar'), ('verificado', 'Verificado · todo OK'), ('falta_emitir', 'Atención · Falta emitir en compañía'), ('pago_post_baja', 'Atención · Pagó después de baja'), ('avisar_vendedor', 'Atención · Avisar al vendedor')], db_index=True, default='pendiente', max_length=30),
        ),
    ]
