# Generated by Django 5.2.7 on 2025-12-07 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('productor', 'Productor'), ('broker', 'Broker'), ('banco', 'Banco'), ('online', 'Venta online'), ('compania_directa', 'Compañía directa'), ('otro', 'Otro')], default='productor', max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('nicho_fuerte', models.CharField(blank=True, max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Competidor',
                'verbose_name_plural': 'Competidores',
            },
        ),
        migrations.CreateModel(
            name='CompetidorCanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo_canal', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('tiktok', 'TikTok'), ('web', 'Página web'), ('whatsapp', 'WhatsApp'), ('linkedin', 'LinkedIn'), ('otro', 'Otro')], max_length=20)),
                ('url_o_user', models.CharField(max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True)),
                ('competidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canales', to='competencia.competidor')),
            ],
            options={
                'verbose_name': 'Canal del competidor',
                'verbose_name_plural': 'Canales de competidores',
            },
        ),
        migrations.CreateModel(
            name='CompetidorPromocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=255)),
                ('tipo_promocion', models.CharField(choices=[('descuento', 'Descuento'), ('cuotas', 'Cuotas'), ('combo', 'Combo de productos'), ('regalo', 'Regalo / beneficio extra'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('canal', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('tiktok', 'TikTok'), ('web', 'Página web'), ('cartel_local', 'Cartel local'), ('cliente', 'Info de cliente'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('vigente', models.BooleanField(default=True)),
                ('notas_condiciones', models.TextField(blank=True)),
                ('competidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promociones', to='competencia.competidor')),
            ],
            options={
                'verbose_name': 'Promoción de competidor',
                'verbose_name_plural': 'Promociones de competidores',
            },
        ),
        migrations.CreateModel(
            name='CompetidorUbicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direccion', models.CharField(max_length=255)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('provincia', models.CharField(blank=True, max_length=100)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('es_principal', models.BooleanField(default=False)),
                ('horario_desde', models.CharField(blank=True, max_length=50)),
                ('horario_hasta', models.CharField(blank=True, max_length=50)),
                ('notas', models.TextField(blank=True)),
                ('competidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones', to='competencia.competidor')),
            ],
            options={
                'verbose_name': 'Ubicación del competidor',
                'verbose_name_plural': 'Ubicaciones de competidores',
            },
        ),
        migrations.CreateModel(
            name='OportunidadCompetencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ramo', models.CharField(max_length=50)),
                ('resultado', models.CharField(choices=[('gano_competidor', 'Ganó el competidor'), ('gano_yo', 'Gané yo'), ('no_cerro', 'No cerró')], max_length=20)),
                ('motivo', models.CharField(choices=[('precio', 'Precio'), ('cuotas', 'Cuotas / financiación'), ('servicio', 'Servicio / atención'), ('siniestros', 'Manejo de siniestros'), ('confianza', 'Confianza / relación'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('fecha', models.DateField()),
                ('notas', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oportunidades_competencia', to='clientes.cliente')),
                ('competidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oportunidades', to='competencia.competidor')),
            ],
            options={
                'verbose_name': 'Oportunidad vs competencia',
                'verbose_name_plural': 'Oportunidades vs competencia',
            },
        ),
        migrations.CreateModel(
            name='PrecioCompetencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ramo', models.CharField(max_length=50)),
                ('tipo_riesgo', models.CharField(max_length=100)),
                ('compania', models.CharField(blank=True, max_length=100)),
                ('suma_asegurada', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('premio_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('moneda', models.CharField(default='ARS', max_length=10)),
                ('fecha_relevamiento', models.DateField()),
                ('fuente', models.CharField(choices=[('cliente', 'Cliente'), ('captura_poliza', 'Copia de póliza'), ('cotizacion_simulada', 'Cotización simulada'), ('otro', 'Otro')], default='cliente', max_length=30)),
                ('notas', models.TextField(blank=True)),
                ('competidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='competencia.competidor')),
            ],
            options={
                'verbose_name': 'Precio de competencia',
                'verbose_name_plural': 'Precios de competencia',
            },
        ),
    ]
