# Generated by Django 5.2.7 on 2025-12-07 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OficinaMapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=255)),
                ('codigo', models.CharField(blank=True, max_length=50)),
                ('direccion', models.CharField(max_length=255)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('horario_desde', models.CharField(blank=True, max_length=50)),
                ('horario_hasta', models.CharField(blank=True, max_length=50)),
                ('url_maps', models.URLField(blank=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Oficina propia (mapa)',
                'verbose_name_plural': 'Oficinas propias (mapa)',
            },
        ),
        migrations.RemoveField(
            model_name='preciocompetencia',
            name='competidor',
        ),
        migrations.RenameField(
            model_name='competidorubicacion',
            old_name='provincia',
            new_name='cobertura',
        ),
        migrations.RemoveField(
            model_name='competidorubicacion',
            name='es_principal',
        ),
        migrations.RemoveField(
            model_name='competidorubicacion',
            name='notas',
        ),
        migrations.AddField(
            model_name='competidorubicacion',
            name='compania',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='competidorubicacion',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='competidorubicacion',
            name='url_maps',
            field=models.URLField(blank=True),
        ),
        migrations.DeleteModel(
            name='CompetidorPromocion',
        ),
        migrations.DeleteModel(
            name='PrecioCompetencia',
        ),
    ]
