# Generated by Django 5.2.7 on 2025-12-08 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencia', '0002_oficinamapa_remove_preciocompetencia_competidor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competidorubicacion',
            name='direccion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='oficinamapa',
            name='direccion',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
