# Generated by Django 5.2.7 on 2025-12-09 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencia', '0003_alter_competidorubicacion_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competidor',
            name='redes',
            field=models.TextField(blank=True, default='', help_text='Links o usuarios de redes sociales (Instagram, web, etc.)'),
        ),
    ]
