# Generated by Django 5.2.7 on 2025-12-09 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencia', '0004_competidor_redes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competidorubicacion',
            name='url_maps',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='oficinamapa',
            name='url_maps',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
