# Generated by Django 5.2.7 on 2025-12-09 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencia', '0005_alter_competidorubicacion_url_maps_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiPrecioReferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cobertura', models.CharField(max_length=100)),
                ('compania', models.CharField(blank=True, max_length=100)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=15)),
                ('notas', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Precio propio de referencia',
                'verbose_name_plural': 'Precios propios de referencia',
            },
        ),
    ]
