# Generated by Django 5.2.7 on 2026-01-26 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polizas', '0009_rename_foto_public_id_cuponrobo_foto_perfil_public_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BajaPoliza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE_ENVIO', 'Enviar la baja'), ('ENVIADA', 'Baja enviada'), ('REALIZADA', 'Baja realizada')], db_index=True, default='PENDIENTE_ENVIO', max_length=20)),
                ('email_destino', models.EmailField(blank=True, default='', max_length=254)),
                ('notas', models.TextField(blank=True, default='')),
                ('enviada_en', models.DateTimeField(blank=True, null=True)),
                ('realizada_en', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('poliza', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='baja_operativa', to='polizas.poliza')),
            ],
            options={
                'verbose_name': 'Baja de Póliza',
                'verbose_name_plural': 'Bajas de Pólizas',
                'indexes': [models.Index(fields=['estado'], name='bajas_bajap_estado_953b86_idx')],
            },
        ),
    ]
