# Generated by Django 5.2.7 on 2026-02-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bajas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorreoCompaniaBaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compania', models.CharField(max_length=150, unique=True, verbose_name='Nombre de la Compañía')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo de Bajas')),
            ],
            options={
                'verbose_name': 'Correo de Compañía para Bajas',
                'verbose_name_plural': 'Correos de Compañías para Bajas',
            },
        ),
    ]
