# Generated by Django 5.2.7 on 2026-02-24 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bajas', '0002_correocompaniabaja'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialBajaPoliza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, choices=[('PENDIENTE_ENVIO', 'Enviar la baja'), ('ENVIADA', 'Baja enviada'), ('REALIZADA', 'Baja realizada')], max_length=20, verbose_name='Estado Anterior')),
                ('estado_nuevo', models.CharField(choices=[('PENDIENTE_ENVIO', 'Enviar la baja'), ('ENVIADA', 'Baja enviada'), ('REALIZADA', 'Baja realizada')], max_length=20, verbose_name='Estado Nuevo')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del movimiento')),
                ('baja_poliza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='bajas.bajapoliza')),
            ],
            options={
                'verbose_name': 'Historial de Baja',
                'verbose_name_plural': 'Historiales de Bajas',
                'ordering': ['-fecha'],
            },
        ),
    ]
