# Generated by Django 5.2.7 on 2026-05-09 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bajas', '0003_historialbajapoliza'),
        ('polizas', '0016_poliza_vendedor_comision'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bajapoliza',
            options={'verbose_name': 'Baja de póliza', 'verbose_name_plural': 'Bajas de pólizas'},
        ),
        migrations.AlterModelOptions(
            name='correocompaniabaja',
            options={'ordering': ['compania'], 'verbose_name': 'Correo de compañía para bajas', 'verbose_name_plural': 'Correos de compañías para bajas'},
        ),
        migrations.AlterModelOptions(
            name='historialbajapoliza',
            options={'ordering': ['-fecha'], 'verbose_name': 'Historial de baja', 'verbose_name_plural': 'Historiales de bajas'},
        ),
        migrations.AddField(
            model_name='bajapoliza',
            name='email_asunto',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='bajapoliza',
            name='email_cuerpo',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='bajapoliza',
            name='email_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='bajapoliza',
            name='email_ok',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='correocompaniabaja',
            name='dias_gracia',
            field=models.PositiveSmallIntegerField(default=3, help_text='Pólizas con mora menor a este valor no entran al proceso de baja.', verbose_name='Días de mora mínimos'),
        ),
        migrations.AlterField(
            model_name='bajapoliza',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE_ENVIO', 'Pendiente de envío'), ('ENVIADA', 'Email enviado a compañía'), ('REALIZADA', 'Baja confirmada por compañía')], db_index=True, default='PENDIENTE_ENVIO', max_length=20),
        ),
        migrations.AlterField(
            model_name='correocompaniabaja',
            name='compania',
            field=models.CharField(help_text="Debe coincidir exactamente con el campo 'compania' de Poliza.", max_length=150, unique=True, verbose_name='Nombre de la compañía'),
        ),
        migrations.AlterField(
            model_name='correocompaniabaja',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Correo de bajas'),
        ),
        migrations.AlterField(
            model_name='historialbajapoliza',
            name='estado_anterior',
            field=models.CharField(blank=True, choices=[('PENDIENTE_ENVIO', 'Pendiente de envío'), ('ENVIADA', 'Email enviado a compañía'), ('REALIZADA', 'Baja confirmada por compañía')], max_length=20, verbose_name='Estado anterior'),
        ),
        migrations.AlterField(
            model_name='historialbajapoliza',
            name='estado_nuevo',
            field=models.CharField(choices=[('PENDIENTE_ENVIO', 'Pendiente de envío'), ('ENVIADA', 'Email enviado a compañía'), ('REALIZADA', 'Baja confirmada por compañía')], max_length=20, verbose_name='Estado nuevo'),
        ),
        migrations.AlterField(
            model_name='historialbajapoliza',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddIndex(
            model_name='bajapoliza',
            index=models.Index(fields=['enviada_en'], name='bajas_bajap_enviada_27f0f4_idx'),
        ),
    ]
