# Generated by Django 5.2.7 on 2026-06-26 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bajas', '0004_alter_bajapoliza_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correocompaniabaja',
            name='email',
            field=models.TextField(help_text='Uno o varios emails separados por coma. Ej: bajas@cia.com, mesa@cia.com', verbose_name='Correo(s) de bajas'),
        ),
    ]
