# Generated by Django 5.2.7 on 2026-06-19 18:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0004_alter_perfil_rol'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TareaCompletada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('enviar', 'Enviar póliza'), ('datos_poliza', 'Datos de la póliza'), ('datos_cliente', 'Datos del cliente'), ('fotos_dni', 'Fotos de DNI'), ('fotos_poliza', 'Fotos del vehículo')], db_index=True, max_length=20)),
                ('poliza_id', models.IntegerField(blank=True, null=True)),
                ('cliente_id', models.IntegerField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('oficina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_completadas', to='usuarios.oficina')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_completadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['oficina', 'creado_en'], name='tareas_tare_oficina_b2a99b_idx'), models.Index(fields=['tipo', 'creado_en'], name='tareas_tare_tipo_d21acf_idx')],
            },
        ),
    ]
