# Generated by Django 5.2.7 on 2026-06-25 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
        ('usuarios', '0005_oficina_whatsapp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('nombre', models.CharField(help_text='Ej: 9 de Julio', max_length=120)),
                ('nacional', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Feriado',
                'verbose_name_plural': 'Feriados',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='TareaFija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Abrir la oficina, Sacar los carteles', max_length=120)),
                ('frecuencia', models.CharField(choices=[('diaria', 'Todos los días'), ('semanal', 'Ciertos días de la semana')], default='diaria', max_length=10)),
                ('dias_semana', models.CharField(blank=True, default='', max_length=20)),
                ('hora_esperada', models.TimeField(blank=True, help_text='Ej: 09:00. Vacío = sin alerta de horario.', null=True)),
                ('requiere_foto', models.BooleanField(default=True)),
                ('activa', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de aparición en la lista.')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('oficina', models.ForeignKey(blank=True, help_text='Vacío = aplica a todas las oficinas.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tareas_fijas', to='usuarios.oficina')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_fijas_a_cargo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tarea fija',
                'verbose_name_plural': 'Tareas fijas',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='CumplimientoTareaFija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('foto_url', models.URLField(blank=True, default='', max_length=600)),
                ('foto_public_id', models.CharField(blank=True, default='', max_length=255)),
                ('cumplido_en', models.DateTimeField(auto_now_add=True)),
                ('oficina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cumplimientos_tareas_fijas', to='usuarios.oficina')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cumplimientos_tareas_fijas', to=settings.AUTH_USER_MODEL)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cumplimientos', to='tareas.tareafija')),
            ],
            options={
                'verbose_name': 'Cumplimiento de tarea fija',
                'verbose_name_plural': 'Cumplimientos de tareas fijas',
                'ordering': ['-cumplido_en'],
                'unique_together': {('tarea', 'oficina', 'fecha')},
            },
        ),
    ]
