# Generated by Django 5.2.7 on 2026-06-26 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_feriado_tareafija_cumplimientotareafija'),
        ('usuarios', '0005_oficina_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='cumplimientotareafija',
            name='estado_tiempo',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AddField(
            model_name='cumplimientotareafija',
            name='puntos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tareafija',
            name='instruccion_foto',
            field=models.CharField(blank=True, default='', help_text='Qué tiene que mostrar la foto. Ej: la cortina abierta.', max_length=200),
        ),
        migrations.AddField(
            model_name='tareafija',
            name='margen_alerta',
            field=models.PositiveIntegerField(default=15, help_text='Minutos de tolerancia tras la hora antes de alertar y restar puntos.'),
        ),
        migrations.AddField(
            model_name='tareafija',
            name='premia_demora',
            field=models.BooleanField(default=False, help_text='Tareas de cierre: cerrar más tarde suma puntos (horas extra) en vez de restar.'),
        ),
        migrations.CreateModel(
            name='AlertaTareaFijaEnviada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('enviada_en', models.DateTimeField(auto_now_add=True)),
                ('oficina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas_tareas_fijas', to='usuarios.oficina')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='tareas.tareafija')),
            ],
            options={
                'verbose_name': 'Alerta de tarea fija enviada',
                'verbose_name_plural': 'Alertas de tareas fijas enviadas',
                'unique_together': {('tarea', 'oficina', 'fecha')},
            },
        ),
    ]
