# Generated by Django 5.2.7 on 2026-06-26 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0007_rename_solicitudes_oficina_e12ff6_idx_solicitudes_oficina_8e1f93_idx_and_more'),
        ('tareas', '0003_cumplimientotareafija_estado_tiempo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cumplimientotareafija',
            name='cargado_por_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cumplimientotareafija',
            name='responsable_empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cumplimientos_tareas_fijas', to='solicitudes.empleado'),
        ),
        migrations.AddField(
            model_name='cumplimientotareafija',
            name='responsable_nombre',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
