# Generated by Django 5.2.7 on 2026-06-27 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0004_cumplimientotareafija_cargado_por_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareafija',
            name='fotos_max',
            field=models.PositiveIntegerField(default=1, help_text='Fotos máximas que se pueden subir. Debe ser >= fotos_min.'),
        ),
        migrations.AddField(
            model_name='tareafija',
            name='fotos_min',
            field=models.PositiveIntegerField(default=1, help_text='Fotos mínimas para que la tarea quede cumplida (verde).'),
        ),
        migrations.CreateModel(
            name='FotoCumplimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_url', models.URLField(max_length=600)),
                ('foto_public_id', models.CharField(blank=True, default='', max_length=255)),
                ('responsable_nombre', models.CharField(blank=True, default='', max_length=120)),
                ('cargado_por_admin', models.BooleanField(default=False)),
                ('subida_en', models.DateTimeField(auto_now_add=True)),
                ('cumplimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='tareas.cumplimientotareafija')),
            ],
            options={
                'verbose_name': 'Foto de cumplimiento',
                'verbose_name_plural': 'Fotos de cumplimiento',
                'ordering': ['subida_en'],
            },
        ),
    ]
