# Generated by Django 5.2.7 on 2025-12-11 03:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaKpi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oficina', models.CharField(blank=True, db_index=True, help_text='Si está vacío, aplica a todas las oficinas.', max_length=80, null=True)),
                ('tipo', models.CharField(choices=[('morosidad', 'Morosidad'), ('bajas', 'Bajas de póliza'), ('produccion', 'Producción'), ('custom', 'Personalizada')], default='morosidad', max_length=40)),
                ('umbral', models.FloatField(help_text='Por ejemplo, 0.2 para 20% de morosidad.')),
                ('activo', models.BooleanField(default=True)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('ultimo_disparo', models.DateTimeField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Alerta de KPI',
                'verbose_name_plural': 'Alertas de KPI',
            },
        ),
        migrations.CreateModel(
            name='ExportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(help_text="Ej.: 'polizas_oficina', 'cobranzas_oficina', etc.", max_length=80)),
                ('parametros', models.JSONField(blank=True, default=dict)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estadisticas_exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de export de estadísticas',
                'verbose_name_plural': 'Logs de exports de estadísticas',
                'ordering': ('-creado_el',),
            },
        ),
        migrations.CreateModel(
            name='KpiDiarioOficina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('oficina', models.CharField(db_index=True, max_length=80)),
                ('polizas_activas', models.PositiveIntegerField(default=0)),
                ('polizas_morosas', models.PositiveIntegerField(default=0)),
                ('cobranzas_del_dia', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('data_extra', models.JSONField(blank=True, default=dict)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'KPI diario por oficina',
                'verbose_name_plural': 'KPIs diarios por oficina',
                'unique_together': {('fecha', 'oficina')},
            },
        ),
        migrations.CreateModel(
            name='PolizaOficinaSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oficina', models.CharField(db_index=True, max_length=80)),
                ('anio', models.PositiveIntegerField(db_index=True)),
                ('mes', models.PositiveIntegerField(db_index=True)),
                ('total_polizas', models.PositiveIntegerField(default=0)),
                ('total_activas', models.PositiveIntegerField(default=0)),
                ('nuevas_mes', models.PositiveIntegerField(default=0)),
                ('bajas_mes', models.PositiveIntegerField(default=0)),
                ('data_extra', models.JSONField(blank=True, default=dict)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Snapshot pólizas por oficina',
                'verbose_name_plural': 'Snapshots pólizas por oficina',
                'unique_together': {('oficina', 'anio', 'mes')},
            },
        ),
    ]
