# Generated by Django 5.2.7 on 2026-02-02 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadisticas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertakpi',
            name='oficina',
            field=models.CharField(blank=True, db_index=True, help_text='Código ("1","2","3") o vacío = todas.', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='kpidiariooficina',
            name='oficina',
            field=models.CharField(choices=[('1', '5 esquinas (1)'), ('2', 'axion (2)'), ('3', 'kilometro 39 (3)'), ('OTRAS', 'Otras / sin mapear'), ('SIN_OFICINA', 'Sin oficina')], db_index=True, help_text='Guardar código normalizado: "1","2","3","OTRAS","SIN_OFICINA".', max_length=80),
        ),
        migrations.AlterField(
            model_name='polizaoficinasnapshot',
            name='oficina',
            field=models.CharField(choices=[('1', '5 esquinas (1)'), ('2', 'axion (2)'), ('3', 'kilometro 39 (3)'), ('OTRAS', 'Otras / sin mapear'), ('SIN_OFICINA', 'Sin oficina')], db_index=True, help_text='Guardar código normalizado: "1","2","3","OTRAS","SIN_OFICINA".', max_length=80),
        ),
    ]
