# Generated by Django 5.2.7 on 2025-12-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balanzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='egreso',
            name='oficina',
            field=models.CharField(blank=True, choices=[('1', '5 esquinas (1)'), ('2', 'axion (2)'), ('3', 'kilometro 39 (3)')], db_index=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='oficina',
            field=models.CharField(blank=True, choices=[('1', '5 esquinas (1)'), ('2', 'axion (2)'), ('3', 'kilometro 39 (3)')], db_index=True, max_length=1, null=True),
        ),
        migrations.AddIndex(
            model_name='egreso',
            index=models.Index(fields=['fecha', 'oficina'], name='balanzes_eg_fecha_fac1c5_idx'),
        ),
        migrations.AddIndex(
            model_name='ingreso',
            index=models.Index(fields=['fecha', 'oficina'], name='balanzes_in_fecha_09ae41_idx'),
        ),
    ]
