# Generated by Django 5.2.7 on 2026-03-16 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balanzes', '0002_egreso_oficina_ingreso_oficina_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='egreso',
            name='forma_pago',
            field=models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('TARJETA', 'Tarjeta'), ('MERCADOPAGO', 'Mercado Pago'), ('OTRO', 'Otro')], default='EFECTIVO', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='egreso',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egresos_cargados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingresos_cargados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='HistorialEgreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('monto_nuevo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('forma_pago_anterior', models.CharField(blank=True, max_length=20)),
                ('forma_pago_nuevo', models.CharField(blank=True, max_length=20)),
                ('detalle', models.CharField(blank=True, max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('egreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='balanzes.egreso')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='HistorialIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('monto_nuevo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('forma_pago_anterior', models.CharField(blank=True, max_length=20)),
                ('forma_pago_nuevo', models.CharField(blank=True, max_length=20)),
                ('detalle', models.CharField(blank=True, max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ingreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='balanzes.ingreso')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
