# Generated by Django 5.2.7 on 2026-04-28 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balanzes', '0004_categoria'),
        ('usuarios', '0003_oficina_responsable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historialegreso',
            options={},
        ),
        migrations.AlterModelOptions(
            name='historialingreso',
            options={},
        ),
        migrations.RenameIndex(
            model_name='egreso',
            new_name='balanzes_eg_fecha_b8315f_idx',
            old_name='balanzes_eg_fecha_fac1c5_idx',
        ),
        migrations.RenameIndex(
            model_name='ingreso',
            new_name='balanzes_in_fecha_7f2a62_idx',
            old_name='balanzes_in_fecha_09ae41_idx',
        ),
        migrations.AlterField(
            model_name='egreso',
            name='oficina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egresos_caja', to='usuarios.oficina'),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='oficina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingresos_caja', to='usuarios.oficina'),
        ),
    ]
