# Generated by Django 5.2.7 on 2026-05-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balanzes', '0005_alter_historialegreso_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingreso',
            name='billetera',
            field=models.CharField(blank=True, help_text='Cuenta destino del estudio (alias, CBU, nombre billetera)', max_length=255, null=True),
        ),
    ]
