# Generated by Django 5.2.7 on 2026-05-12 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balanzes', '0006_ingreso_billetera'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ingreso',
            name='nota_verificacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='verificada',
            field=models.BooleanField(default=False, help_text='¿La transferencia fue verificada con el comprobante?'),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='verificada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='verificada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_verificadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
