# Generated by Django 5.2.7 on 2026-05-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balanzes', '0007_ingreso_nota_verificacion_ingreso_verificada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingreso',
            name='cuit_remitente',
            field=models.CharField(blank=True, help_text='CUIT/CUIL de quien transfirió', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='nro_operacion',
            field=models.CharField(blank=True, help_text='N° de operación/comprobante de la transferencia', max_length=60, null=True),
        ),
    ]
