# Generated by Django 5.2.7 on 2025-12-26 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('mensaje', models.TextField()),
                ('filtros', models.JSONField(blank=True, default=dict)),
                ('oficina', models.CharField(blank=True, default='', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enviada_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campanias_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaniaEnvioLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_id', models.IntegerField(blank=True, null=True)),
                ('numero', models.CharField(max_length=64)),
                ('estado', models.CharField(choices=[('ok', 'OK'), ('error', 'Error')], max_length=16)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='marketing.campania')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['campania', 'numero'], name='marketing_c_campani_4e6c3c_idx'), models.Index(fields=['created_at'], name='marketing_c_created_6a2f44_idx')],
            },
        ),
    ]
