# Generated by Django 5.2.7 on 2026-03-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campania',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIANDO', 'Enviando'), ('ENVIADA', 'Enviada'), ('PAUSADA', 'Pausada'), ('CANCELADA', 'Cancelada')], db_index=True, default='BORRADOR', max_length=16),
        ),
        migrations.AddField(
            model_name='campania',
            name='total_destinatarios',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campania',
            name='total_enviados',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campania',
            name='total_errores',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campania',
            name='total_invalidos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campania',
            name='total_omitidos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campania',
            name='ultima_ejecucion_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaniaenviolog',
            name='mensaje_renderizado',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='campaniaenviolog',
            name='numero_normalizado',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='campaniaenviolog',
            name='poliza_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaniaenviolog',
            name='provider',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='campaniaenviolog',
            name='provider_meta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='campaniaenviolog',
            name='estado',
            field=models.CharField(choices=[('ok', 'OK'), ('error', 'Error'), ('invalido', 'Inválido'), ('omitido', 'Omitido'), ('dry_run', 'Dry run')], max_length=16),
        ),
        migrations.AddIndex(
            model_name='campaniaenviolog',
            index=models.Index(fields=['campania', 'numero_normalizado'], name='marketing_c_campani_6c66cd_idx'),
        ),
        migrations.AddIndex(
            model_name='campaniaenviolog',
            index=models.Index(fields=['campania', 'estado'], name='marketing_c_campani_6381bb_idx'),
        ),
    ]
