# Generated by Django 5.2.7 on 2026-03-07 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_campania_estado_campania_total_destinatarios_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaniaenviolog',
            name='campania',
        ),
        migrations.CreateModel(
            name='HistorialMensajeMarketing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('filtros', models.JSONField(blank=True, default=dict)),
                ('oficina', models.CharField(blank=True, default='', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ejecutado_at', models.DateTimeField(blank=True, null=True)),
                ('dry_run', models.BooleanField(default=False)),
                ('total_polizas_match', models.PositiveIntegerField(default=0)),
                ('total_destinatarios', models.PositiveIntegerField(default=0)),
                ('total_enviados', models.PositiveIntegerField(default=0)),
                ('total_errores', models.PositiveIntegerField(default=0)),
                ('total_invalidos', models.PositiveIntegerField(default=0)),
                ('total_omitidos', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketing_historial_creado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistorialMensajeMarketingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_id', models.IntegerField(blank=True, null=True)),
                ('poliza_id', models.IntegerField(blank=True, null=True)),
                ('numero', models.CharField(blank=True, default='', max_length=64)),
                ('numero_normalizado', models.CharField(blank=True, default='', max_length=32)),
                ('estado', models.CharField(choices=[('ok', 'OK'), ('error', 'Error'), ('invalido', 'Inválido'), ('omitido', 'Omitido'), ('dry_run', 'Dry run')], max_length=16)),
                ('error', models.TextField(blank=True, default='')),
                ('mensaje_renderizado', models.TextField(blank=True, default='')),
                ('provider', models.CharField(blank=True, default='', max_length=32)),
                ('provider_meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('historial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='marketing.historialmensajemarketing')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Campania',
        ),
        migrations.DeleteModel(
            name='CampaniaEnvioLog',
        ),
        migrations.AddIndex(
            model_name='historialmensajemarketinglog',
            index=models.Index(fields=['historial', 'numero'], name='marketing_h_histori_c72070_idx'),
        ),
        migrations.AddIndex(
            model_name='historialmensajemarketinglog',
            index=models.Index(fields=['historial', 'numero_normalizado'], name='marketing_h_histori_2118f5_idx'),
        ),
        migrations.AddIndex(
            model_name='historialmensajemarketinglog',
            index=models.Index(fields=['historial', 'estado'], name='marketing_h_histori_5d6910_idx'),
        ),
        migrations.AddIndex(
            model_name='historialmensajemarketinglog',
            index=models.Index(fields=['created_at'], name='marketing_h_created_259203_idx'),
        ),
    ]
