# Generated by Django 5.2.7 on 2026-03-08 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_remove_campaniaenviolog_campania_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historialmensajemarketing',
            options={'ordering': ['-created_at'], 'verbose_name': 'Historial de Marketing', 'verbose_name_plural': 'Historiales de Marketing'},
        ),
        migrations.AlterModelOptions(
            name='historialmensajemarketinglog',
            options={'ordering': ['id']},
        ),
        migrations.RemoveIndex(
            model_name='historialmensajemarketinglog',
            name='marketing_h_histori_c72070_idx',
        ),
        migrations.RemoveIndex(
            model_name='historialmensajemarketinglog',
            name='marketing_h_histori_2118f5_idx',
        ),
        migrations.RemoveIndex(
            model_name='historialmensajemarketinglog',
            name='marketing_h_histori_5d6910_idx',
        ),
        migrations.RemoveIndex(
            model_name='historialmensajemarketinglog',
            name='marketing_h_created_259203_idx',
        ),
        migrations.RemoveField(
            model_name='historialmensajemarketing',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historialmensajemarketing',
            name='ejecutado_at',
        ),
        migrations.RemoveField(
            model_name='historialmensajemarketing',
            name='total_destinatarios',
        ),
        migrations.RemoveField(
            model_name='historialmensajemarketinglog',
            name='cliente_id',
        ),
        migrations.RemoveField(
            model_name='historialmensajemarketinglog',
            name='numero_normalizado',
        ),
        migrations.RemoveField(
            model_name='historialmensajemarketinglog',
            name='poliza_id',
        ),
        migrations.RemoveField(
            model_name='historialmensajemarketinglog',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='historialmensajemarketinglog',
            name='provider_meta',
        ),
        migrations.AlterField(
            model_name='historialmensajemarketing',
            name='dry_run',
            field=models.BooleanField(default=False, help_text='Si es True, no se enviaron mensajes reales.'),
        ),
        migrations.AlterField(
            model_name='historialmensajemarketing',
            name='mensaje',
            field=models.TextField(help_text='Cuerpo del mensaje con variables como {marca}, {modelo}, etc.'),
        ),
        migrations.AlterField(
            model_name='historialmensajemarketing',
            name='oficina',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historialmensajemarketing',
            name='total_enviados',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historialmensajemarketing',
            name='total_errores',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historialmensajemarketing',
            name='total_invalidos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historialmensajemarketing',
            name='total_omitidos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historialmensajemarketing',
            name='total_polizas_match',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historialmensajemarketinglog',
            name='error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historialmensajemarketinglog',
            name='estado',
            field=models.CharField(choices=[('ok', 'Enviado'), ('error', 'Error'), ('invalido', 'Número Inválido'), ('dry_run', 'Simulación')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historialmensajemarketinglog',
            name='mensaje_renderizado',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='historialmensajemarketinglog',
            name='numero',
            field=models.CharField(max_length=30),
        ),
    ]
