# Generated by Django 5.2.7 on 2026-03-08 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_alter_historialmensajemarketing_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historialmensajemarketing',
            options={'ordering': ['-created_at'], 'verbose_name': 'Historial de Marketing'},
        ),
        migrations.RemoveField(
            model_name='historialmensajemarketing',
            name='total_omitidos',
        ),
        migrations.AddField(
            model_name='historialmensajemarketing',
            name='ejecutado_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historialmensajemarketing',
            name='total_destinatarios',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historialmensajemarketinglog',
            name='cliente_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historialmensajemarketinglog',
            name='numero_normalizado',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='historialmensajemarketinglog',
            name='poliza_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historialmensajemarketing',
            name='dry_run',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historialmensajemarketing',
            name='mensaje',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='historialmensajemarketing',
            name='oficina',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='historialmensajemarketing',
            name='total_enviados',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historialmensajemarketing',
            name='total_errores',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historialmensajemarketing',
            name='total_invalidos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historialmensajemarketing',
            name='total_polizas_match',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historialmensajemarketinglog',
            name='error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='historialmensajemarketinglog',
            name='estado',
            field=models.CharField(choices=[('ok', 'OK'), ('error', 'Error'), ('invalido', 'Inválido'), ('dry_run', 'Simulación')], max_length=16),
        ),
        migrations.AlterField(
            model_name='historialmensajemarketinglog',
            name='mensaje_renderizado',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='historialmensajemarketinglog',
            name='numero',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
