# Generated by Django 5.2.7 on 2026-03-09 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0005_alter_historialmensajemarketing_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historialmensajemarketing',
            options={'ordering': ['-created_at'], 'verbose_name': 'Historial de Marketing', 'verbose_name_plural': 'Historiales de Marketing'},
        ),
        migrations.AlterModelOptions(
            name='historialmensajemarketinglog',
            options={'ordering': ['id'], 'verbose_name': 'Log de Envío'},
        ),
        migrations.AddField(
            model_name='historialmensajemarketing',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketing_historial_creado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historialmensajemarketing',
            name='total_omitidos',
            field=models.PositiveIntegerField(default=0, help_text='Mensajes omitidos (ej: ya enviados previamente).'),
        ),
        migrations.AddField(
            model_name='historialmensajemarketinglog',
            name='provider',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='historialmensajemarketinglog',
            name='provider_meta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='historialmensajemarketing',
            name='dry_run',
            field=models.BooleanField(default=False, help_text='Indica si fue una simulación.'),
        ),
        migrations.AlterField(
            model_name='historialmensajemarketing',
            name='filtros',
            field=models.JSONField(blank=True, default=dict, help_text='Copia de los filtros aplicados.'),
        ),
        migrations.AlterField(
            model_name='historialmensajemarketing',
            name='mensaje',
            field=models.TextField(help_text='Cuerpo del mensaje con variables como {nombre}, {apellido}, {marca}, etc.'),
        ),
        migrations.AlterField(
            model_name='historialmensajemarketing',
            name='total_destinatarios',
            field=models.PositiveIntegerField(default=0, help_text='Total de destinatarios únicos (mensajes reales).'),
        ),
        migrations.AlterField(
            model_name='historialmensajemarketing',
            name='total_polizas_match',
            field=models.PositiveIntegerField(default=0, help_text='Total de pólizas que coincidieron con los filtros.'),
        ),
        migrations.AlterField(
            model_name='historialmensajemarketinglog',
            name='estado',
            field=models.CharField(choices=[('ok', 'OK'), ('error', 'Error'), ('invalido', 'Inválido'), ('omitido', 'Omitido'), ('dry_run', 'Dry run')], max_length=16),
        ),
        migrations.AlterField(
            model_name='historialmensajemarketinglog',
            name='mensaje_renderizado',
            field=models.TextField(blank=True, default='', help_text='Mensaje final con {nombre}, {apellido}, etc. ya reemplazados.'),
        ),
    ]
