# Generated by Django 5.2.7 on 2025-10-22 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=255)),
                ('partido', models.CharField(max_length=100)),
                ('localidad', models.CharField(max_length=100)),
                ('contrato', models.FileField(blank=True, null=True, upload_to='contratos_alquiler/')),
                ('requisitos', models.TextField(blank=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('precio_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('aumento_cada_n_meses', models.PositiveIntegerField(help_text='Ej: cada 4 meses')),
                ('porcentaje_aumento', models.DecimalField(decimal_places=2, help_text='Ej: 10.00 para 10%', max_digits=5)),
                ('comisionado', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inquilino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('dni', models.CharField(max_length=20)),
                ('direccion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=255)),
                ('localidad', models.CharField(max_length=100)),
                ('partido', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('alquiler', 'Alquiler'), ('venta', 'Venta')], max_length=10)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('reservada', 'Reservada'), ('vendida', 'Vendida'), ('alquilada', 'Alquilada')], default='disponible', max_length=15)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_publicacion', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('dni', models.CharField(max_length=20)),
                ('direccion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CuotaAlquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('fecha_vencimiento', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pagado', models.BooleanField(default=False)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('forma_pago', models.CharField(blank=True, max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('alquiler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='inmuebles.alquiler')),
            ],
        ),
        migrations.AddField(
            model_name='alquiler',
            name='inquilinos',
            field=models.ManyToManyField(related_name='alquileres', to='inmuebles.inquilino'),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='propiedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alquileres', to='inmuebles.propiedad'),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='propietarios',
            field=models.ManyToManyField(related_name='propiedades', to='inmuebles.propietario'),
        ),
    ]
