# Generated by Django 5.2.7 on 2026-05-25 00:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('balanzes', '0008_ingreso_cuit_remitente_ingreso_nro_operacion'),
        ('pagos', '0011_pago_estado_verificacion_pago_verificacion_nota_and_more'),
        ('usuarios', '0004_alter_perfil_rol'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioFijo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Edenor, Telecentro, Alquiler Oficina Centro', max_length=120)),
                ('proveedor', models.CharField(blank=True, default='', help_text='Razón social del proveedor (opcional). Ej: Edenor S.A.', max_length=120)),
                ('categoria', models.CharField(help_text='Ej: Servicios Públicos, Pago de Alquiler', max_length=120)),
                ('monto_estimado', models.DecimalField(decimal_places=2, default=0, help_text='Monto orientativo. El monto real se ingresa al pagar.', max_digits=12)),
                ('dia_vencimiento', models.PositiveSmallIntegerField(help_text='Día del mes en que vence (1-31). Ej: 10, 18, 30')),
                ('forma_pago_default', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('MERCADOPAGO', 'Mercado Pago')], default='TRANSFERENCIA', max_length=20)),
                ('activo', models.BooleanField(default=True, help_text='Si está inactivo, no se generan pagos mensuales.')),
                ('notas', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_creados', to=settings.AUTH_USER_MODEL)),
                ('oficina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_fijos', to='usuarios.oficina')),
            ],
            options={
                'verbose_name': 'Servicio Fijo',
                'verbose_name_plural': 'Servicios Fijos',
                'ordering': ['oficina', 'dia_vencimiento', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='PagoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(help_text='Formato AAAA-MM. Ej: 2026-05', max_length=7)),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('VENCIDO', 'Vencido'), ('OMITIDO', 'Omitido')], db_index=True, default='PENDIENTE', max_length=15)),
                ('monto_real', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('hora_pago', models.DateTimeField(blank=True, null=True)),
                ('forma_pago', models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('MERCADOPAGO', 'Mercado Pago')], default='', max_length=20)),
                ('comprobante_url', models.URLField(blank=True, default='', help_text='URL del comprobante en Cloudinary', max_length=600)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('egreso', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pago_servicio_origen', to='balanzes.egreso')),
                ('medio_cobro', models.ForeignKey(blank=True, help_text='Billetera/cuenta desde la que se pagó', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_servicios', to='pagos.mediocobro')),
                ('pagado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_pagados', to=settings.AUTH_USER_MODEL)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='servicios.serviciofijo')),
            ],
            options={
                'verbose_name': 'Pago de Servicio',
                'verbose_name_plural': 'Pagos de Servicios',
                'ordering': ['-periodo', 'servicio__dia_vencimiento'],
            },
        ),
        migrations.AddIndex(
            model_name='serviciofijo',
            index=models.Index(fields=['oficina', 'activo'], name='servicios_s_oficina_ecd48f_idx'),
        ),
        migrations.AddIndex(
            model_name='serviciofijo',
            index=models.Index(fields=['dia_vencimiento'], name='servicios_s_dia_ven_c6b400_idx'),
        ),
        migrations.AddIndex(
            model_name='pagoservicio',
            index=models.Index(fields=['periodo', 'estado'], name='servicios_p_periodo_79f3c7_idx'),
        ),
        migrations.AddIndex(
            model_name='pagoservicio',
            index=models.Index(fields=['estado', 'fecha_vencimiento'], name='servicios_p_estado_9cb7eb_idx'),
        ),
        migrations.AddConstraint(
            model_name='pagoservicio',
            constraint=models.UniqueConstraint(fields=('servicio', 'periodo'), name='un_pago_por_servicio_y_periodo'),
        ),
    ]
