# Generated by Django 5.2.7 on 2026-05-25 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0011_pago_estado_verificacion_pago_verificacion_nota_and_more'),
        ('servicios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagoservicio',
            name='comprobante_url',
            field=models.URLField(blank=True, default='', max_length=600),
        ),
        migrations.AlterField(
            model_name='pagoservicio',
            name='medio_cobro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_servicios', to='pagos.mediocobro'),
        ),
        migrations.AlterField(
            model_name='serviciofijo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='serviciofijo',
            name='categoria',
            field=models.CharField(help_text='Categoría del servicio (cargar desde CategoriaServicio)', max_length=120),
        ),
        migrations.AlterField(
            model_name='serviciofijo',
            name='dia_vencimiento',
            field=models.PositiveSmallIntegerField(help_text='Día del mes en que vence (1-31)'),
        ),
        migrations.AlterField(
            model_name='serviciofijo',
            name='monto_estimado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='CategoriaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('color', models.CharField(blank=True, default='sky', help_text='Color para identificación visual (sky, emerald, amber, rose, etc.)', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorias_servicios_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Categoría de Servicio',
                'verbose_name_plural': 'Categorías de Servicios',
                'ordering': ['nombre'],
            },
        ),
    ]
