# Generated by Django 5.2.7 on 2025-10-22 04:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polizas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PolizaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('POLIZA', 'Póliza'), ('VEHICULO', 'Vehículo'), ('DOC', 'Documento'), ('FOTO', 'Foto'), ('CUOTA', 'Cuota'), ('PAGO', 'Pago'), ('GRUA', 'Grúa'), ('SINIESTRO', 'Siniestro'), ('COM', 'Comunicación'), ('NOTA', 'Nota'), ('SISTEMA', 'Sistema')], default='POLIZA', max_length=16)),
                ('tipo', models.CharField(choices=[('POLIZA_CREAR', 'Creación de póliza'), ('POLIZA_EDITAR', 'Edición de póliza'), ('POLIZA_CAMBIAR_ESTADO', 'Cambio de estado'), ('POLIZA_CAMBIO_TITULAR', 'Cambio de titular'), ('POLIZA_CAMBIO_COBERTURA', 'Cambio de cobertura'), ('POLIZA_CAMBIO_PREMIO', 'Cambio de premio'), ('PERFIL_CAMBIAR', 'Cambio de foto de perfil'), ('VEHICULO_EDITAR', 'Edición de vehículo'), ('DOC_SUBIR', 'Documento subido'), ('DOC_BORRAR', 'Documento eliminado'), ('DOC_CAMBIAR_VTO', 'Cambio de vencimiento de documento'), ('DOC_VALIDAR', 'Documento validado'), ('DOC_FALTANTE', 'Documento faltante'), ('FOTO_SUBIR', 'Foto subida'), ('FOTO_BORRAR', 'Foto eliminada'), ('CUOTA_GENERAR', 'Cuotas generadas'), ('CUOTA_RECALCULAR', 'Cuotas recalculadas'), ('PAGO_REGISTRAR', 'Pago registrado'), ('PAGO_ANULAR', 'Pago anulado'), ('PAGO_FALLAR', 'Pago fallido'), ('PAGO_APLICAR_A_CUOTA', 'Pago aplicado a cuota'), ('GRUA_ADHESION_CREAR', 'Adhesión creada'), ('GRUA_ADHESION_ACTUALIZAR', 'Adhesión actualizada'), ('GRUA_ADHESION_BAJA', 'Adhesión dada de baja'), ('GRUA_SERVICIO_SOLICITAR', 'Servicio solicitado'), ('GRUA_SERVICIO_CERRAR', 'Servicio cerrado'), ('SINIESTRO_ABRIR', 'Siniestro abierto'), ('SINIESTRO_ACTUALIZAR', 'Siniestro actualizado'), ('SINIESTRO_CERRAR', 'Siniestro cerrado'), ('COM_EMAIL_ENVIADO', 'Email enviado'), ('COM_EMAIL_EVENTO', 'Evento email'), ('COM_WHATSAPP_EVENTO', 'Evento WhatsApp'), ('COM_LLAMADA', 'Llamada registrada'), ('NOTA', 'Nota'), ('ALERTA_VTO_PROXIMO', 'Alerta de vencimiento'), ('ALERTA_CUOTA_VENCIDA', 'Cuota vencida'), ('MILESTONE_COMPLETADO', 'Hito completado')], max_length=32)),
                ('severidad', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Advertencia'), ('ERROR', 'Error'), ('ACTION', 'Acción')], default='INFO', max_length=8)),
                ('mensaje', models.CharField(max_length=255)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('subject_type', models.CharField(blank=True, default='', max_length=40)),
                ('subject_id', models.IntegerField(blank=True, null=True)),
                ('actor_name', models.CharField(blank=True, default='', max_length=150)),
                ('source', models.CharField(choices=[('USER', 'Usuario'), ('SYSTEM', 'Sistema'), ('WEBHOOK', 'Webhook'), ('BATCH', 'Proceso batch')], default='USER', max_length=12)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_poliza', to=settings.AUTH_USER_MODEL)),
                ('poliza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='polizas.poliza')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['poliza', 'created_at'], name='historia_po_poliza__2e0ced_idx'), models.Index(fields=['categoria'], name='historia_po_categor_b9a938_idx'), models.Index(fields=['tipo'], name='historia_po_tipo_7e588b_idx'), models.Index(fields=['subject_type', 'subject_id'], name='historia_po_subject_528d5d_idx'), models.Index(fields=['idempotency_key'], name='historia_po_idempot_1147f2_idx')],
            },
        ),
    ]
