# Generated by Django 5.2.7 on 2026-04-22 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficina',
            name='ultramsg_instance_id',
            field=models.CharField(blank=True, help_text='Ej: instance171359', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='oficina',
            name='ultramsg_token',
            field=models.CharField(blank=True, help_text='El token largo de la API de UltraMsg', max_length=64, null=True),
        ),
    ]
