# Generated by Django 5.2.7 on 2026-04-23 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_oficina_ultramsg_instance_id_oficina_ultramsg_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='oficina',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oficinas_bajo_mando', to=settings.AUTH_USER_MODEL),
        ),
    ]
