# Generated by Django 5.2.7 on 2026-05-03 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_oficina_responsable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador Global'), ('OFICINA', 'Personal de Oficina'), ('VENDEDOR', 'Vendedor Externo')], default='OFICINA', max_length=20),
        ),
    ]
