# Generated by Django 5.2.7 on 2026-06-25 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_perfil_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficina',
            name='whatsapp',
            field=models.CharField(blank=True, default='', help_text="WhatsApp de la oficina (ej: 5492284123456) para el botón 'Pedir mis papeles' del portal.", max_length=32),
        ),
    ]
