# Generated by Django 5.2.7 on 2026-03-18 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recaudacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cierrecaja',
            name='diferencia',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Declarado - Sistema', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='cierrecaja',
            name='estado_auditoria',
            field=models.CharField(blank=True, default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='cierrecaja',
            name='monto_sistema',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cálculo automático de balances', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='cierrecaja',
            name='monto_declarado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Lo que el usuario contó físicamente', max_digits=12, null=True),
        ),
    ]
