# Generated by Django 5.2.7 on 2026-03-18 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recaudacion', '0002_cierrecaja_diferencia_cierrecaja_estado_auditoria_and_more'),
        ('solicitudes', '0007_rename_solicitudes_oficina_e12ff6_idx_solicitudes_oficina_8e1f93_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cierrecaja',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cierres_caja', to='solicitudes.empleado'),
        ),
        migrations.AlterField(
            model_name='cierrecaja',
            name='diferencia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='cierrecaja',
            name='monto_declarado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='cierrecaja',
            name='monto_sistema',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
