# Generated by Django 5.2.7 on 2026-06-26 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recaudacion', '0003_cierrecaja_empleado_alter_cierrecaja_diferencia_and_more'),
        ('usuarios', '0005_oficina_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='cierrecaja',
            name='turno',
            field=models.CharField(blank=True, choices=[('mediodia', 'Mediodía'), ('noche', 'Noche')], default='', max_length=10),
        ),
        migrations.CreateModel(
            name='HorarioCierreCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mediodia', models.TimeField(blank=True, help_text='Ej: 13:00. Vacío = sin cierre de mediodía.', null=True)),
                ('noche', models.TimeField(blank=True, help_text='Ej: 20:00. Vacío = sin cierre de noche.', null=True)),
                ('aviso_min', models.PositiveIntegerField(default=30, help_text='Minutos antes para avisar con el pop-up.')),
                ('tolerancia_min', models.PositiveIntegerField(default=5, help_text='Minutos de tolerancia después de la hora.')),
                ('activo', models.BooleanField(default=True)),
                ('oficina', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='horario_cierre', to='usuarios.oficina')),
            ],
            options={
                'verbose_name': 'Horario de cierre de caja',
                'verbose_name_plural': 'Horarios de cierre de caja',
            },
        ),
    ]
