# Generated by Django 5.2.7 on 2025-10-22 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Siniestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=100)),
                ('poliza', models.CharField(max_length=100)),
                ('marca_auto', models.CharField(max_length=50)),
                ('modelo_auto', models.CharField(max_length=50)),
                ('ano_auto', models.PositiveIntegerField()),
                ('descripcion', models.TextField()),
                ('responsabilidad', models.CharField(choices=[('CHOCO', 'Nuestro asegurado chocó'), ('CHOCARON', 'Nuestro asegurado fue chocado')], max_length=8)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiniestroEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_evento', models.DateTimeField()),
                ('descripcion_evento', models.TextField()),
                ('siniestro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='siniestros.siniestro')),
            ],
        ),
    ]
