# Generated by Django 5.2.7 on 2026-04-29 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_cliente_oficina_and_more'),
        ('polizas', '0013_planpago_poliza_plan_pago'),
        ('siniestros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siniestro',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Falta Documentación'), ('DENUNCIADO', 'Denunciado en Cía'), ('INSPECCION', 'Inspección Pendiente'), ('LIQUIDACION', 'En Liquidación'), ('CERRADO', 'Cerrado / Finalizado')], default='PENDIENTE', max_length=15),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='fecha_siniestro',
            field=models.DateField(blank=True, help_text='Cuándo ocurrió realmente el accidente', null=True),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='nro_reclamo_cia',
            field=models.CharField(blank=True, help_text='N° de siniestro que da la compañía', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='patente',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='tercero_compania',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='tercero_nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='tercero_patente',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='tercero_poliza',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='siniestro',
            name='tercero_telefono',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='siniestro',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siniestros', to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='siniestro',
            name='poliza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siniestros', to='polizas.poliza'),
        ),
        migrations.AlterField(
            model_name='siniestro',
            name='responsabilidad',
            field=models.CharField(choices=[('CHOCO', 'Nuestro asegurado chocó'), ('CHOCARON', 'Nuestro asegurado fue chocado'), ('ROBO', 'Robo / Hurto'), ('INCENDIO', 'Incendio'), ('OTRO', 'Otro / Varios')], max_length=15),
        ),
    ]
