# Generated by Django 5.2.7 on 2026-05-13 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siniestros', '0002_siniestro_estado_siniestro_fecha_siniestro_and_more'),
        ('usuarios', '0004_alter_perfil_rol'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siniestro',
            options={'ordering': ['-fecha_creacion']},
        ),
        migrations.AddField(
            model_name='siniestro',
            name='oficina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='siniestros', to='usuarios.oficina'),
        ),
        migrations.AlterField(
            model_name='siniestro',
            name='fecha_siniestro',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siniestro',
            name='nro_reclamo_cia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
