# Generated by Django 5.2.7 on 2026-05-26 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siniestros', '0003_alter_siniestro_options_siniestro_oficina_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siniestro',
            options={},
        ),
        migrations.RemoveField(
            model_name='siniestro',
            name='oficina',
        ),
        migrations.AlterField(
            model_name='siniestro',
            name='ano_auto',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siniestro',
            name='fecha_siniestro',
            field=models.DateField(blank=True, help_text='Cuándo ocurrió realmente el accidente', null=True),
        ),
        migrations.AlterField(
            model_name='siniestro',
            name='marca_auto',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='siniestro',
            name='modelo_auto',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='siniestro',
            name='nro_reclamo_cia',
            field=models.CharField(blank=True, help_text='N° de siniestro que da la compañía', max_length=50, null=True),
        ),
    ]
