# Generated by Django 5.2.7 on 2026-05-26 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siniestros', '0004_alter_siniestro_options_remove_siniestro_oficina_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiniestroFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000)),
                ('public_id', models.CharField(max_length=255)),
                ('nombre', models.CharField(blank=True, default='', max_length=255)),
                ('mime', models.CharField(blank=True, default='image/jpeg', max_length=100)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('siniestro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='siniestros.siniestro')),
                ('subida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='siniestro_fotos_subidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Foto de siniestro',
                'verbose_name_plural': 'Fotos de siniestros',
                'ordering': ['-fecha_creacion', '-id'],
            },
        ),
    ]
