# Generated by Django 5.2.7 on 2025-10-22 04:53

import django.db.models.deletion
import solicitudes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=80, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(default=solicitudes.models.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudSeguro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=32, unique=True)),
                ('cliente_nombre', models.CharField(blank=True, max_length=128)),
                ('cliente_dni', models.CharField(blank=True, max_length=32)),
                ('telefono', models.CharField(blank=True, help_text='Teléfono del cliente (WhatsApp / E.164 o similar)', max_length=32, null=True)),
                ('vehiculo_marca', models.CharField(blank=True, max_length=64)),
                ('vehiculo_modelo', models.CharField(blank=True, max_length=64)),
                ('vehiculo_anio', models.PositiveIntegerField(blank=True, null=True)),
                ('vehiculo_patente', models.CharField(blank=True, max_length=16)),
                ('vehiculo_vin', models.CharField(blank=True, max_length=32)),
                ('cobertura_solicitada', models.CharField(blank=True, max_length=128)),
                ('compania_preferida', models.CharField(blank=True, max_length=64)),
                ('motivo', models.CharField(choices=[('ALTA_POLIZA', 'Alta de póliza'), ('ASISTENCIA_GRUA', 'Asistencia de grúa'), ('OTRO', 'Otro')], db_index=True, default='ALTA_POLIZA', max_length=20)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('EN_REVISION', 'En revisión'), ('VIGENTE_24H', 'Constancia 12 h vigente'), ('CONVERTIDA', 'Convertida a póliza'), ('VENCIDA', 'Vencida'), ('CANCELADA', 'Cancelada'), ('TERMINADA', 'Terminada')], default='BORRADOR', max_length=16)),
                ('inicio', models.DateTimeField(blank=True, null=True)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('responsable_nombre', models.CharField(blank=True, db_index=True, help_text='Nombre de quien carga la solicitud (obligatorio)', max_length=80)),
                ('asignado_en', models.DateTimeField(blank=True, null=True)),
                ('responsable', models.CharField(blank=True, db_index=True, max_length=80)),
                ('qr_payload', models.URLField(blank=True, max_length=512)),
                ('poliza_id', models.IntegerField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('prioridad', models.CharField(blank=True, default='NORMAL', max_length=16)),
                ('terminada_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(default=solicitudes.models.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('responsable_empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes', to='solicitudes.empleado')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DNI_FRENTE', 'DNI (frente)'), ('DNI_DORSO', 'DNI (dorso)'), ('PASAPORTE_FRENTE', 'Pasaporte (frente)'), ('PASAPORTE_DORSO', 'Pasaporte (dorso)'), ('REGISTRO', 'Registro de conducir'), ('REGISTRO_FRENTE', 'Registro de Conducir (frente)'), ('REGISTRO_DORSO', 'Registro de Conducir (dorso)'), ('CEDULA_VERDE', 'Cédula verde'), ('CEDULA_VERDE_FRENTE', 'Cédula Verde (frente)'), ('CEDULA_VERDE_DORSO', 'Cédula Verde (dorso)'), ('CEDULA_AZUL', 'Cédula azul'), ('CEDULA_AZUL_FRENTE', 'Cédula Azul (frente)'), ('CEDULA_AZUL_DORSO', 'Cédula Azul (dorso)'), ('TITULO', 'Título'), ('VTV', 'VTV'), ('PATENTE', 'Foto patente'), ('ENTORNO', 'Foto del entorno'), ('FRENTE', 'Frente vehículo'), ('LATERAL_IZQ', 'Lateral izquierdo'), ('LATERAL_DER', 'Lateral derecho'), ('TRASERA', 'Trasera'), ('VIN', 'VIN'), ('EQUIPO_GNC', 'Equipo GNC'), ('OBLEA_GNC', 'Oblea GNC'), ('OTRO', 'Otro')], default='OTRO', max_length=32)),
                ('url', models.URLField(max_length=512)),
                ('public_id', models.CharField(blank=True, db_index=True, max_length=256)),
                ('nombre', models.CharField(blank=True, max_length=128)),
                ('mime', models.CharField(blank=True, max_length=64)),
                ('vencimiento', models.DateField(blank=True, null=True)),
                ('notas', models.CharField(blank=True, max_length=256)),
                ('creado_en', models.DateTimeField(default=solicitudes.models.now)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='solicitudes.solicitudseguro')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.AddIndex(
            model_name='solicitudseguro',
            index=models.Index(fields=['motivo', 'estado'], name='solicitudes_motivo_7f0a79_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudseguro',
            index=models.Index(fields=['responsable', 'estado'], name='solicitudes_respons_4f9dbc_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudseguro',
            index=models.Index(fields=['responsable_nombre', 'estado'], name='solicitudes_respons_8fe335_idx'),
        ),
        migrations.AddIndex(
            model_name='solicituddocumento',
            index=models.Index(fields=['solicitud', 'tipo'], name='solicitudes_solicit_8be8b7_idx'),
        ),
        migrations.AddIndex(
            model_name='solicituddocumento',
            index=models.Index(fields=['tipo'], name='solicitudes_tipo_66f6aa_idx'),
        ),
    ]
