# Generated by Django 5.2.7 on 2025-10-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicituddocumento',
            name='tipo',
            field=models.CharField(choices=[('DNI_FRENTE', 'DNI (frente)'), ('DNI_DORSO', 'DNI (dorso)'), ('PASAPORTE_FRENTE', 'Pasaporte (frente)'), ('PASAPORTE_DORSO', 'Pasaporte (dorso)'), ('CEDULA_VERDE', 'Cédula verde'), ('CEDULA_VERDE_FRENTE', 'Cédula Verde (frente)'), ('CEDULA_VERDE_DORSO', 'Cédula Verde (dorso)'), ('CEDULA_AZUL', 'Cédula azul'), ('CEDULA_AZUL_FRENTE', 'Cédula Azul (frente)'), ('CEDULA_AZUL_DORSO', 'Cédula Azul (dorso)'), ('TITULO', 'Título'), ('PATENTE', 'Foto patente'), ('FRENTE', 'Frente vehículo'), ('LATERAL_IZQ', 'Lateral izquierdo'), ('LATERAL_DER', 'Lateral derecho'), ('TRASERA', 'Trasera'), ('EQUIPO_GNC', 'Equipo GNC'), ('OBLEA_GNC', 'Oblea GNC'), ('OTRO', 'Otro')], default='OTRO', max_length=32),
        ),
    ]
