# Generated by Django 5.2.7 on 2025-11-11 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0002_alter_solicituddocumento_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudseguro',
            name='alta_compania',
            field=models.BooleanField(db_index=True, default=False, help_text='Marcada cuando ya se dio el alta en la compañía'),
        ),
        migrations.AddField(
            model_name='solicitudseguro',
            name='enviar_poliza',
            field=models.BooleanField(db_index=True, default=False, help_text='Marcada cuando se envió la póliza al cliente'),
        ),
    ]
