# Generated by Django 5.2.7 on 2025-11-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0003_solicitudseguro_alta_compania_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudseguro',
            name='oficina',
            field=models.CharField(blank=True, help_text='Oficina / sucursal asociada (snapshot para filtros operativos)', max_length=64),
        ),
    ]
