# Generated by Django 5.2.7 on 2026-02-18 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0004_solicitudseguro_oficina'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='solicituddocumento',
            index=models.Index(fields=['solicitud', 'public_id'], name='solicitudes_solicit_f8b9fe_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudseguro',
            index=models.Index(fields=['estado', 'alta_compania'], name='solicitudes_estado_0b9266_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudseguro',
            index=models.Index(fields=['estado', 'enviar_poliza'], name='solicitudes_estado_b478b1_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudseguro',
            index=models.Index(fields=['oficina', 'estado'], name='solicitudes_oficina_e12ff6_idx'),
        ),
    ]
