# Generated by Django 5.2.7 on 2026-03-13 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0005_solicituddocumento_solicitudes_solicit_f8b9fe_idx_and_more'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='oficina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados_solicitudes', to='usuarios.oficina'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nombre',
            field=models.CharField(db_index=True, max_length=80),
        ),
        migrations.AlterUniqueTogether(
            name='empleado',
            unique_together={('nombre', 'oficina')},
        ),
    ]
