# Generated by Django 5.2.7 on 2026-03-13 05:02

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0006_empleado_oficina_alter_empleado_nombre_and_more'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        # 💉 BISTURÍ SQL DEFINITIVO: Asignamos la oficina 1 (5 Esquinas) a los vacíos. 
        # Así evitamos el error de texto vacío Y el error de no-nulo al mismo tiempo.
        migrations.RunSQL(
            "UPDATE solicitudes_solicitudseguro SET oficina = '1' WHERE oficina = '';",
            reverse_sql=migrations.RunSQL.noop
        ),
        
        migrations.RenameIndex(
            model_name='solicitudseguro',
            new_name='solicitudes_oficina_8e1f93_idx',
            old_name='solicitudes_oficina_e12ff6_idx',
        ),
        migrations.AlterField(
            model_name='solicitudseguro',
            name='oficina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_sucursal', to='usuarios.oficina'),
        ),
    ]