# Generated by Django 5.2.7 on 2026-07-16 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0007_rename_solicitudes_oficina_e12ff6_idx_solicitudes_oficina_8e1f93_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudseguro',
            name='motivo',
            field=models.CharField(choices=[('ALTA_POLIZA', 'Alta de póliza'), ('OTRO', 'Otro')], db_index=True, default='ALTA_POLIZA', max_length=20),
        ),
    ]
