# Generated by Django 5.2.7 on 2026-07-23 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0008_alter_solicitudseguro_motivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudseguro',
            name='fin',
        ),
        migrations.RemoveField(
            model_name='solicitudseguro',
            name='inicio',
        ),
        migrations.RemoveField(
            model_name='solicitudseguro',
            name='qr_payload',
        ),
    ]
