# Generated by Django 5.2.7 on 2025-10-22 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('dni_cuit_cuil', models.CharField(max_length=20)),
                ('direccion', models.TextField(blank=True)),
                ('localidad', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('archivo_dni', models.URLField(blank=True, max_length=500, null=True)),
                ('archivo_dni_frente', models.URLField(blank=True, max_length=500, null=True)),
                ('archivo_dni_dorso', models.URLField(blank=True, max_length=500, null=True)),
                ('archivo_pasaporte_frente', models.URLField(blank=True, max_length=500, null=True)),
                ('archivo_pasaporte_dorso', models.URLField(blank=True, max_length=500, null=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('COMPLETO', 'Completo')], default='BORRADOR', max_length=10)),
            ],
            options={
                'ordering': ['apellido', 'nombre'],
                'indexes': [models.Index(fields=['apellido', 'nombre'], name='clientes_cl_apellid_894bd6_idx'), models.Index(fields=['dni_cuit_cuil'], name='clientes_cl_dni_cui_045fc9_idx'), models.Index(fields=['telefono'], name='clientes_cl_telefon_6177bc_idx'), models.Index(fields=['email'], name='clientes_cl_email_eae461_idx')],
            },
        ),
    ]
