# Generated by Django 5.2.7 on 2026-02-14 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
