# Generated by Django 5.2.7 on 2026-03-13 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_cliente_telefono'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='oficina',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_ficha', to='usuarios.oficina'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['oficina'], name='clientes_cl_oficina_935df7_idx'),
        ),
    ]
