# Generated by Django 5.2.7 on 2026-06-01 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_alter_cliente_oficina'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='partido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
