# Generated by Django 5.2.7 on 2026-06-23 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_cliente_partido'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='portal_token',
            field=models.CharField(blank=True, db_index=True, help_text='Token del link del portal del asegurado. Regenerable.', max_length=64, null=True, unique=True),
        ),
    ]
