# Generated by Django 5.2.7 on 2026-07-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_cliente_portal_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='dni_cuit_cuil',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
