# Generated by Django 5.2.7 on 2026-02-17 00:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polizas', '0009_rename_foto_public_id_cuponrobo_foto_perfil_public_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanGrua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('km_incluidos', models.PositiveIntegerField(default=100)),
                ('precio_mensual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('proveedor_nombre', models.CharField(blank=True, default='', max_length=120)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProveedorGrua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160)),
                ('patente_camion', models.CharField(db_index=True, max_length=20)),
                ('modelo_camion', models.CharField(blank=True, default='', max_length=120)),
                ('anio_camion', models.PositiveIntegerField(default=0)),
                ('foto_camion_1_url', models.URLField(blank=True, default='')),
                ('foto_camion_1_public_id', models.CharField(blank=True, default='', max_length=255)),
                ('foto_camion_2_url', models.URLField(blank=True, default='')),
                ('foto_camion_2_public_id', models.CharField(blank=True, default='', max_length=255)),
                ('licencia_url', models.URLField(blank=True, default='')),
                ('licencia_public_id', models.CharField(blank=True, default='', max_length=255)),
                ('vtv_url', models.URLField(blank=True, default='')),
                ('vtv_public_id', models.CharField(blank=True, default='', max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['patente_camion'], name='gruas_prove_patente_521e0d_idx'), models.Index(fields=['activo', 'creado_en'], name='gruas_prove_activo_b1e64f_idx')],
            },
        ),
        migrations.CreateModel(
            name='AdhesionGrua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ACTIVA', 'ACTIVA'), ('PAUSADA', 'PAUSADA'), ('CANCELADA', 'CANCELADA'), ('VENCIDA', 'VENCIDA')], default='ACTIVA', max_length=12)),
                ('fecha_activacion', models.DateField(default=django.utils.timezone.localdate)),
                ('carencia_dias', models.PositiveIntegerField(default=15)),
                ('motivo_cancelacion', models.TextField(blank=True, default='')),
                ('cancelada_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('poliza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adhesiones_grua', to='polizas.poliza')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adhesiones', to='gruas.plangrua')),
            ],
            options={
                'indexes': [models.Index(fields=['poliza', 'estado'], name='gruas_adhes_poliza__596696_idx'), models.Index(fields=['estado', 'fecha_activacion'], name='gruas_adhes_estado_f82407_idx')],
            },
        ),
    ]
