# Generated by Django 5.2.7 on 2026-02-17 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gruas', '0001_initial'),
        ('polizas', '0009_rename_foto_public_id_cuponrobo_foto_perfil_public_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudGrua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ABIERTA', 'ABIERTA'), ('ASIGNADA', 'ASIGNADA'), ('EN_CAMINO', 'EN_CAMINO'), ('CERRADA', 'CERRADA'), ('CANCELADA', 'CANCELADA')], default='ABIERTA', max_length=12)),
                ('motivo', models.CharField(blank=True, default='', max_length=160)),
                ('notas', models.TextField(blank=True, default='')),
                ('origen_direccion', models.CharField(blank=True, default='', max_length=220)),
                ('origen_maps_url', models.URLField(blank=True, default='')),
                ('origen_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('origen_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('destino_direccion', models.CharField(blank=True, default='', max_length=220)),
                ('destino_maps_url', models.URLField(blank=True, default='')),
                ('destino_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('destino_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('km_estimados', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('asignada_en', models.DateTimeField(blank=True, null=True)),
                ('cerrada_en', models.DateTimeField(blank=True, null=True)),
                ('cancelada_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('adhesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='gruas.adhesiongrua')),
                ('poliza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_grua', to='polizas.poliza')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes', to='gruas.proveedorgrua')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('AUTO', 'AUTO'), ('LUGAR', 'LUGAR'), ('REGISTRO', 'REGISTRO'), ('DNI', 'DNI')], max_length=12)),
                ('url', models.URLField()),
                ('public_id', models.CharField(max_length=255)),
                ('descripcion', models.CharField(blank=True, default='', max_length=180)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='gruas.solicitudgrua')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=40)),
                ('detalle', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='gruas.solicitudgrua')),
            ],
        ),
        migrations.AddIndex(
            model_name='solicitudgrua',
            index=models.Index(fields=['estado', 'creado_en'], name='gruas_solic_estado_a89b4b_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudgrua',
            index=models.Index(fields=['poliza', 'estado'], name='gruas_solic_poliza__42c49d_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudgrua',
            index=models.Index(fields=['proveedor', 'estado'], name='gruas_solic_proveed_9d1f9f_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudfoto',
            index=models.Index(fields=['solicitud', 'tipo'], name='gruas_solic_solicit_05ca2b_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudevento',
            index=models.Index(fields=['solicitud', 'creado_en'], name='gruas_solic_solicit_7d7da9_idx'),
        ),
    ]
