# Generated by Django 5.2.7 on 2026-02-17 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gruas', '0002_solicitudgrua_solicitudfoto_solicitudevento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudgrua',
            name='destino_maps_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='solicitudgrua',
            name='origen_maps_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
    ]
