# Generated by Django 5.2.7 on 2026-02-17 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gruas', '0003_alter_solicitudgrua_destino_maps_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedorgrua',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddIndex(
            model_name='proveedorgrua',
            index=models.Index(fields=['telefono'], name='gruas_prove_telefon_ac9523_idx'),
        ),
    ]
