# Generated by Django 5.2.7 on 2026-02-17 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gruas', '0004_proveedorgrua_telefono_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudgrua',
            name='destino_localidad',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='solicitudgrua',
            name='origen_localidad',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
