# Generated by Django 5.2.7 on 2026-03-20 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nombre', models.CharField(max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('marca_auto', models.CharField(max_length=100)),
                ('modelo_auto', models.CharField(max_length=100)),
                ('anio_auto', models.IntegerField()),
                ('tiene_gnc', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('VENDIDA', 'Vendida (Póliza)'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OpcionCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compania', models.CharField(max_length=100)),
                ('tipo_cobertura', models.CharField(max_length=100)),
                ('costo_compania', models.DecimalField(decimal_places=2, max_digits=12)),
                ('porcentaje_comision', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('precio_cliente', models.DecimalField(decimal_places=2, max_digits=12)),
                ('detalles_cobertura', models.TextField(blank=True, null=True)),
                ('es_recomendada', models.BooleanField(default=False)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='cotizaciones.cotizacion')),
            ],
        ),
    ]
