# Generated by Django 5.2.7 on 2026-03-21 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompaniaSeguro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('comision_default', models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje de comisión oficial (Ej: 18.00)', max_digits=5)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='opcioncotizacion',
            name='compania',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='opciones', to='cotizaciones.companiaseguro'),
        ),
    ]
