# Generated by Django 5.2.7 on 2026-03-21 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0002_companiaseguro_alter_opcioncotizacion_compania'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCobertura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='opcioncotizacion',
            name='tipo_cobertura',
        ),
        migrations.AddField(
            model_name='opcioncotizacion',
            name='cobertura',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='opciones', to='cotizaciones.tipocobertura'),
            preserve_default=False,
        ),
    ]
