# Generated by Django 5.2.7 on 2026-03-21 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0003_tipocobertura_remove_opcioncotizacion_tipo_cobertura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcioncotizacion',
            name='detalles_cobertura',
            field=models.JSONField(blank=True, default=list, help_text="Lista de beneficios (ej: ['Granizo', 'Grúa'])"),
        ),
    ]
