# Generated by Django 5.2.7 on 2026-03-21 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0004_alter_opcioncotizacion_detalles_cobertura'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipocobertura',
            name='beneficios_default',
            field=models.JSONField(blank=True, default=list, help_text='Lista de beneficios por defecto'),
        ),
    ]
