# Generated by Django 5.2.7 on 2026-03-24 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0005_tipocobertura_beneficios_default'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipocobertura',
            options={'ordering': ['compania__nombre', 'nombre']},
        ),
        migrations.AddField(
            model_name='companiaseguro',
            name='antiguedad_maxima',
            field=models.IntegerField(default=25, help_text='Antigüedad máxima del vehículo permitida en años (Ej: 25)'),
        ),
        migrations.AddField(
            model_name='tipocobertura',
            name='compania',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coberturas', to='cotizaciones.companiaseguro'),
        ),
        migrations.AlterField(
            model_name='tipocobertura',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
