# Generated by Django 5.2.7 on 2026-03-24 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0006_alter_tipocobertura_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcioncotizacion',
            name='suma_asegurada',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
    ]
