# Generated by Django 5.2.7 on 2026-03-25 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0007_opcioncotizacion_suma_asegurada'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('margen_ganancia_default', models.DecimalField(decimal_places=2, default=35.0, help_text='Margen de ganancia global por defecto (%)', max_digits=5)),
            ],
        ),
        migrations.AddField(
            model_name='opcioncotizacion',
            name='objetivo_ganancia',
            field=models.DecimalField(decimal_places=2, default=35.0, max_digits=5),
        ),
    ]
