# Generated by Django 5.2.7 on 2026-04-23 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0008_configuracionglobal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companiaseguro',
            name='logo_url',
            field=models.URLField(blank=True, help_text='URL del logo de la aseguradora', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tipocobertura',
            name='fotos_requeridas',
            field=models.JSONField(blank=True, default=list, help_text="Lista de fotos obligatorias (ej: ['FRENTE', 'TRASERA', 'TECHO_CRISTAL'])"),
        ),
    ]
