# Generated by Django 5.2.7 on 2026-04-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0009_companiaseguro_logo_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotizacion',
            options={},
        ),
        migrations.AddField(
            model_name='tipocobertura',
            name='documentos_requeridos',
            field=models.JSONField(blank=True, default=list, help_text='Lista de documentos obligatorios'),
        ),
        migrations.AlterField(
            model_name='companiaseguro',
            name='antiguedad_maxima',
            field=models.IntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='companiaseguro',
            name='comision_default',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='companiaseguro',
            name='logo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='configuracionglobal',
            name='margen_ganancia_default',
            field=models.DecimalField(decimal_places=2, default=35.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='estado',
            field=models.CharField(default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='opcioncotizacion',
            name='detalles_cobertura',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='tipocobertura',
            name='beneficios_default',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='tipocobertura',
            name='fotos_requeridas',
            field=models.JSONField(blank=True, default=list, help_text='Lista de fotos obligatorias'),
        ),
    ]
