# Generated by Django 5.2.7 on 2026-04-30 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0010_alter_cotizacion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipocobertura',
            name='cuotas_a_generar',
            field=models.IntegerField(default=6, help_text='Cantidad de cuotas a generar por defecto'),
        ),
        migrations.AddField(
            model_name='tipocobertura',
            name='genera_cupones_robo',
            field=models.BooleanField(default=False, help_text='¿Esta cobertura incluye cuponera de robo?'),
        ),
    ]
