# Generated by Django 5.2.7 on 2025-12-09 16:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geoitem',
            old_name='activa',
            new_name='activo',
        ),
        migrations.RenameField(
            model_name='geoitem',
            old_name='descripcion',
            new_name='nota',
        ),
        migrations.RemoveField(
            model_name='geoitem',
            name='contacto',
        ),
        migrations.RemoveField(
            model_name='geoitem',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='geoitem',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='geoitem',
            name='longitud',
        ),
        migrations.RemoveField(
            model_name='geoitem',
            name='precio_estimado',
        ),
        migrations.AddField(
            model_name='geoitem',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='geoitem',
            name='direccion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='geoitem',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='geoitem',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='geoitem',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='geoitem',
            name='tipo',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('prospecto', 'Prospecto'), ('oficina_rival', 'Oficina rival'), ('cartel', 'Cartel / publicidad'), ('alquiler_disponible', 'Alquiler disponible'), ('potencial', 'Ubicación potencial')], max_length=30),
        ),
    ]
