# Generated by Django 5.2.7 on 2025-10-22 04:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poliza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compania', models.CharField(max_length=100)),
                ('numero_poliza', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('sin_numero', models.BooleanField(default=False, help_text='Marcar mientras la póliza aún no tiene número asignado por la compañía.')),
                ('cobertura', models.CharField(max_length=100)),
                ('oficina', models.CharField(max_length=100)),
                ('patente', models.CharField(db_index=True, max_length=10)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('anio', models.IntegerField()),
                ('tipo', models.CharField(choices=[('Auto', 'Auto'), ('Camioneta', 'Camioneta'), ('Camion', 'Camión'), ('Moto', 'Moto'), ('Trailer', 'Trailer')], default='Auto', max_length=20)),
                ('precio_cuota', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cantidad_cuotas', models.IntegerField(default=1)),
                ('primer_pago', models.DateField()),
                ('fecha_vencimiento', models.DateField(db_index=True)),
                ('dias_a_vencer', models.IntegerField()),
                ('fecha_emision', models.DateField()),
                ('alertas', models.TextField(blank=True)),
                ('archivo_poliza', models.FileField(blank=True, null=True, upload_to='polizas/documentos/')),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('vencida', 'Vencida'), ('cancelada', 'Cancelada'), ('finalizada', 'Finalizada')], db_index=True, default='activa', max_length=20)),
                ('fase', models.CharField(choices=[('PRELIMINAR', 'Preliminar'), ('DEFINITIVA', 'Definitiva')], db_index=True, default='PRELIMINAR', max_length=11)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('motivo_baja', models.CharField(blank=True, choices=[('INCUMPLIMIENTO_PAGO', 'Incumplimiento de pago'), ('MIGRACION_COMPANIA', 'Migración a otra compañía'), ('VENTA_VEHICULO', 'Venta del vehículo'), ('SIN_USO', 'Sin uso'), ('OTRO', 'Otro')], max_length=40, null=True)),
                ('observaciones_baja', models.TextField(blank=True, default='')),
                ('foto_perfil_url', models.TextField(blank=True, default='')),
                ('foto_perfil_public_id', models.CharField(blank=True, default='', max_length=200)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polizas', to='clientes.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='FotoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PATENTE', 'Patente visible'), ('FRENTE', 'Frente'), ('LATERAL_IZQ', 'Lateral izquierda'), ('LATERAL_DER', 'Lateral derecha'), ('TRASERA', 'Trasera'), ('VIN', 'VIN / chasis'), ('INTERIOR', 'Interior'), ('OTRA', 'Otra'), ('ENTORNO', 'Entorno'), ('EQUIPO_GNC', 'Equipo GNC'), ('OBLEA_GNC', 'Oblea GNC')], default='OTRA', max_length=15)),
                ('url', models.TextField()),
                ('public_id', models.CharField(blank=True, default='', max_length=200)),
                ('origen', models.CharField(choices=[('ONBOARDING', 'Onboarding póliza'), ('OFICINA', 'Ingreso a oficina'), ('SINIESTRO', 'Siniestro'), ('OTRO', 'Otro')], default='ONBOARDING', max_length=12)),
                ('subido_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('poliza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos_vehiculo', to='polizas.poliza')),
            ],
            options={
                'ordering': ['-subido_en'],
            },
        ),
        migrations.CreateModel(
            name='PolizaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CEDULA_VERDE', 'Cédula verde'), ('CEDULA_AZUL', 'Cédula azul'), ('REGISTRO_CONDUCIR', 'Registro de Conducir'), ('TITULO', 'Título del vehículo'), ('VTV', 'VTV'), ('OBLEA_GNC', 'Oblea GNC'), ('SEGURO_ANEXO_GRUA', 'Anexo grúa'), ('OTRO', 'Otro')], default='OTRO', max_length=30)),
                ('url', models.TextField()),
                ('public_id', models.CharField(blank=True, default='', max_length=200)),
                ('nombre', models.CharField(blank=True, default='', max_length=255)),
                ('mime', models.CharField(blank=True, default='', max_length=100)),
                ('vencimiento', models.DateField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, default='')),
                ('lado', models.CharField(blank=True, choices=[('FRENTE', 'Frente'), ('DORSO', 'Dorso')], default='', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('poliza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='polizas.poliza')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='poliza',
            index=models.Index(fields=['estado', 'fecha_vencimiento'], name='polizas_pol_estado_435cae_idx'),
        ),
        migrations.AddIndex(
            model_name='poliza',
            index=models.Index(fields=['cliente', 'estado'], name='polizas_pol_cliente_ab2a0d_idx'),
        ),
        migrations.AddIndex(
            model_name='poliza',
            index=models.Index(fields=['patente', 'estado'], name='polizas_pol_patente_0ed187_idx'),
        ),
        migrations.AddIndex(
            model_name='poliza',
            index=models.Index(fields=['cliente', 'fecha_vencimiento'], name='polizas_pol_cliente_102157_idx'),
        ),
        migrations.AddIndex(
            model_name='poliza',
            index=models.Index(fields=['fase', 'estado'], name='polizas_pol_fase_bb57b5_idx'),
        ),
        migrations.AddIndex(
            model_name='poliza',
            index=models.Index(fields=['sin_numero', 'estado'], name='polizas_pol_sin_num_44b6f8_idx'),
        ),
        migrations.AddIndex(
            model_name='poliza',
            index=models.Index(fields=['cliente', 'patente'], name='polizas_pol_cliente_ec4c85_idx'),
        ),
        migrations.AddIndex(
            model_name='fotovehiculo',
            index=models.Index(fields=['poliza', 'tipo'], name='polizas_fot_poliza__6b8686_idx'),
        ),
        migrations.AddIndex(
            model_name='polizadocumento',
            index=models.Index(fields=['poliza', 'tipo'], name='polizas_pol_poliza__88c002_idx'),
        ),
        migrations.AddIndex(
            model_name='polizadocumento',
            index=models.Index(fields=['poliza', 'tipo', 'lado'], name='polizas_pol_poliza__c2714c_idx'),
        ),
        migrations.AddIndex(
            model_name='polizadocumento',
            index=models.Index(fields=['poliza', 'vencimiento'], name='polizas_pol_poliza__10dbc5_idx'),
        ),
        migrations.AddConstraint(
            model_name='polizadocumento',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('tipo__in', ['VTV', 'OBLEA_GNC', 'REGISTRO_CONDUCIR']), _negated=True), ('vencimiento__isnull', False), _connector='OR'), name='polizadoc_vto_req_vtv_reg_gnc'),
        ),
        migrations.AddConstraint(
            model_name='polizadocumento',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('tipo__in', ['CEDULA_VERDE', 'CEDULA_AZUL']), ('lado__in', ['', 'FRENTE', 'DORSO'])), models.Q(models.Q(('tipo__in', ['CEDULA_VERDE', 'CEDULA_AZUL']), _negated=True), ('lado__exact', '')), _connector='OR'), name='polizadoc_lado_solo_en_cedulas'),
        ),
    ]
