# Generated by Django 5.2.7 on 2025-10-22 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polizas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='polizadocumento',
            name='polizadoc_vto_req_vtv_reg_gnc',
        ),
        migrations.AlterField(
            model_name='fotovehiculo',
            name='tipo',
            field=models.CharField(choices=[('PATENTE', 'Patente visible'), ('FRENTE', 'Frente'), ('LATERAL_IZQ', 'Lateral izquierda'), ('LATERAL_DER', 'Lateral derecha'), ('TRASERA', 'Trasera'), ('INTERIOR', 'Interior'), ('OTRA', 'Otra'), ('EQUIPO_GNC', 'Equipo GNC'), ('OBLEA_GNC', 'Oblea GNC')], default='OTRA', max_length=15),
        ),
        migrations.AlterField(
            model_name='polizadocumento',
            name='tipo',
            field=models.CharField(choices=[('CEDULA_VERDE', 'Cédula verde'), ('CEDULA_AZUL', 'Cédula azul'), ('REGISTRO_CONDUCIR', 'Registro de Conducir'), ('TITULO', 'Título del vehículo'), ('OBLEA_GNC', 'Oblea GNC'), ('SEGURO_ANEXO_GRUA', 'Anexo grúa'), ('OTRO', 'Otro')], default='OTRO', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='polizadocumento',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('tipo', 'REGISTRO_CONDUCIR'), _negated=True), ('vencimiento__isnull', False), _connector='OR'), name='polizadoc_vto_req_registro'),
        ),
    ]
