# Generated by Django 5.2.7 on 2025-10-23 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polizas', '0002_remove_polizadocumento_polizadoc_vto_req_vtv_reg_gnc_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='polizadocumento',
            name='polizadoc_vto_req_registro',
        ),
        migrations.AlterField(
            model_name='polizadocumento',
            name='tipo',
            field=models.CharField(choices=[('CEDULA_VERDE', 'Cédula verde'), ('CEDULA_AZUL', 'Cédula azul'), ('TITULO', 'Título del vehículo'), ('OBLEA_GNC', 'Oblea GNC'), ('SEGURO_ANEXO_GRUA', 'Anexo grúa'), ('OTRO', 'Otro')], default='OTRO', max_length=30),
        ),
    ]
