# Generated by Django 5.2.7 on 2025-10-31 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polizas', '0003_remove_polizadocumento_polizadoc_vto_req_registro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotovehiculo',
            name='etiquetas',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
