# Generated by Django 5.2.7 on 2025-10-31 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polizas', '0004_fotovehiculo_etiquetas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotovehiculo',
            name='origen',
            field=models.CharField(choices=[('ONBOARDING', 'Onboarding póliza'), ('OFICINA', 'Ingreso a oficina'), ('SINIESTRO', 'Siniestro'), ('SOLICITUD', 'Desde solicitud'), ('OTRO', 'Otro')], default='ONBOARDING', max_length=12),
        ),
    ]
