# Generated by Django 5.2.7 on 2025-11-18 04:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polizas', '0005_alter_fotovehiculo_origen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotovehiculo',
            name='tipo',
            field=models.CharField(choices=[('PATENTE', 'Patente visible'), ('FRENTE', 'Frente'), ('LATERAL_IZQ', 'Lateral izquierda'), ('LATERAL_DER', 'Lateral derecha'), ('TRASERA', 'Trasera'), ('INTERIOR', 'Interior'), ('RUEDA_AUXILIO', 'Rueda de auxilio'), ('RUEDA_AUX', 'Rueda aux. (alias)'), ('TUBO_GNC', 'Tubo GNC'), ('EQUIPO_GNC', 'Equipo GNC'), ('OBLEA_GNC', 'Oblea GNC'), ('OTRA', 'Otra')], default='OTRA', max_length=15),
        ),
        migrations.AlterField(
            model_name='polizadocumento',
            name='tipo',
            field=models.CharField(choices=[('CEDULA_VERDE', 'Cédula verde'), ('CEDULA_AZUL', 'Cédula azul'), ('TITULO', 'Título del vehículo'), ('VTV', 'VTV'), ('OBLEA_GNC', 'Oblea GNC'), ('PERMISO', 'Permiso de circulación'), ('PERMISO_CIRCULACION', 'Permiso de circulación (alias)'), ('SEGURO_ANEXO_GRUA', 'Anexo grúa'), ('OTRO', 'Otro')], default='OTRO', max_length=30),
        ),
        migrations.CreateModel(
            name='CuponRobo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_desde', models.DateField()),
                ('periodo_hasta', models.DateField()),
                ('fecha_vencimiento', models.DateField(db_index=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada'), ('VENCIDA', 'Vencida')], db_index=True, default='PENDIENTE', max_length=10)),
                ('foto_url', models.TextField(blank=True, default='')),
                ('foto_public_id', models.CharField(blank=True, default='', max_length=200)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('poliza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cupones_robo', to='polizas.poliza')),
            ],
            options={
                'ordering': ['fecha_vencimiento', 'id'],
                'indexes': [models.Index(fields=['poliza', 'fecha_vencimiento'], name='polizas_cup_poliza__e3fd50_idx'), models.Index(fields=['poliza', 'estado'], name='polizas_cup_poliza__6bf75a_idx')],
            },
        ),
    ]
