# Generated by Django 5.2.7 on 2025-11-18 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polizas', '0006_alter_fotovehiculo_tipo_alter_polizadocumento_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuponrobo',
            name='fecha_pago',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cuponrobo',
            name='medio_cobro',
            field=models.CharField(blank=True, default='', help_text='Alias de billetera / medio usado para pagar este cupón.', max_length=100),
        ),
        migrations.AddField(
            model_name='cuponrobo',
            name='notas',
            field=models.TextField(blank=True, default=''),
        ),
    ]
