# Generated by Django 5.2.7 on 2025-12-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polizas', '0007_cuponrobo_fecha_pago_cuponrobo_medio_cobro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuponrobo',
            name='monto',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto abonado por este cupón (egreso hacia compañía).', max_digits=10, null=True),
        ),
    ]
