# Generated by Django 5.2.7 on 2026-01-08 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polizas', '0008_cuponrobo_monto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuponrobo',
            old_name='foto_public_id',
            new_name='foto_perfil_public_id',
        ),
    ]
