# Generated by Django 5.2.7 on 2026-03-13 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_cliente_oficina_and_more'),
        ('polizas', '0009_rename_foto_public_id_cuponrobo_foto_perfil_public_id'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poliza',
            name='oficina',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polizas_ficha', to='usuarios.oficina'),
        ),
        migrations.AddIndex(
            model_name='poliza',
            index=models.Index(fields=['oficina'], name='polizas_pol_oficina_cc27b5_idx'),
        ),
    ]
