# Generated by Django 5.2.7 on 2026-04-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polizas', '0011_cobertura_compania_alter_poliza_cobertura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotovehiculo',
            name='tipo',
            field=models.CharField(default='OTRA', max_length=100),
        ),
        migrations.AlterField(
            model_name='polizadocumento',
            name='tipo',
            field=models.CharField(default='OTRO', max_length=100),
        ),
    ]
