# Generated by Django 5.2.7 on 2026-04-29 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polizas', '0012_alter_fotovehiculo_tipo_alter_polizadocumento_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: NRE 3 Cuotas o Equidad Anual c/Robo', max_length=150)),
                ('cuotas_a_generar', models.IntegerField(default=1, help_text='Cantidad de recibos normales a crear')),
                ('meses_vigencia_total', models.IntegerField(default=1, help_text='Duración total de la póliza en meses (ej: 12)')),
                ('frecuencia_refacturacion', models.IntegerField(default=1, help_text='Cada cuántos meses se refactura el precio')),
                ('genera_cupones_robo', models.BooleanField(default=False, help_text='¿Este plan genera chequera de robo?')),
                ('cupones_robo_a_generar', models.IntegerField(default=0, help_text='Cantidad de cupones de robo')),
                ('activa', models.BooleanField(default=True)),
                ('compania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes', to='polizas.compania')),
            ],
            options={
                'ordering': ['compania__nombre', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='poliza',
            name='plan_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polizas', to='polizas.planpago'),
        ),
    ]
