# Generated by Django 5.2.7 on 2026-04-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polizas', '0013_planpago_poliza_plan_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poliza',
            name='plan_pago',
        ),
        migrations.AddField(
            model_name='cobertura',
            name='cuotas_a_generar',
            field=models.IntegerField(default=6, help_text='Cantidad de cuotas/recibos a generar por defecto (Ej: 12)'),
        ),
        migrations.AddField(
            model_name='cobertura',
            name='genera_cupones_robo',
            field=models.BooleanField(default=False, help_text='¿Esta cobertura incluye cuponera de robo?'),
        ),
        migrations.DeleteModel(
            name='PlanPago',
        ),
    ]
