# Generated by Django 5.2.7 on 2026-04-30 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0011_tipocobertura_cuotas_a_generar_and_more'),
        ('polizas', '0014_remove_poliza_plan_pago_cobertura_cuotas_a_generar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poliza',
            name='cobertura_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polizas', to='cotizaciones.tipocobertura'),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='compania_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polizas', to='cotizaciones.companiaseguro'),
        ),
        migrations.DeleteModel(
            name='Cobertura',
        ),
        migrations.DeleteModel(
            name='Compania',
        ),
    ]
