# Generated by Django 5.2.7 on 2026-05-03 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0010_alter_alertaenviada_fecha'),
        ('polizas', '0015_alter_poliza_cobertura_obj_alter_poliza_compania_obj_and_more'),
        ('usuarios', '0004_alter_perfil_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='poliza',
            name='vendedor',
            field=models.ForeignKey(blank=True, help_text='El vendedor externo asociado a esta póliza.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polizas_vendidas', to='usuarios.perfil'),
        ),
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de liquidar'), ('LIQUIDADA', 'Pagada al vendedor')], db_index=True, default='PENDIENTE', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_liquidacion', models.DateTimeField(blank=True, null=True)),
                ('cuota', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comision_generada', to='pagos.cuota')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comisiones_ganadas', to='usuarios.perfil')),
            ],
            options={
                'verbose_name': 'Comisión',
                'verbose_name_plural': 'Comisiones',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
