# Generated by Django 5.2.7 on 2026-05-09 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polizas', '0016_poliza_vendedor_comision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poliza',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('vencida', 'Vencida'), ('cancelada', 'Cancelada'), ('finalizada', 'Finalizada'), ('en_verificacion', 'En verificación')], db_index=True, default='activa', max_length=20),
        ),
    ]
