# Generated by Django 5.2.7 on 2026-05-10 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polizas', '0017_alter_poliza_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='poliza',
            name='es_renovacion',
            field=models.BooleanField(db_index=True, default=False, help_text='True si esta póliza fue creada como renovación de otra existente.'),
        ),
        migrations.AddField(
            model_name='poliza',
            name='poliza_origen',
            field=models.ForeignKey(blank=True, help_text='Póliza original de la que se renovó esta.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renovaciones_generadas', to='polizas.poliza'),
        ),
    ]
