# Generated by Django 5.2.7 on 2026-05-22 01:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polizas', '0018_poliza_es_renovacion_poliza_poliza_origen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PolizaContactoRenovacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('LLAMADA', 'Llamada'), ('EMAIL', 'Email'), ('MANUAL', 'Marcado manual')], default='MANUAL', max_length=20)),
                ('nota', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('poliza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos_renovacion', to='polizas.poliza')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contactos_renovacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['poliza', '-creado_en'], name='polizas_pol_poliza__2d535a_idx'), models.Index(fields=['-creado_en'], name='polizas_pol_creado__77b84f_idx')],
            },
        ),
    ]
