# Generated by Django 5.2.7 on 2026-05-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polizas', '0019_polizacontactorenovacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='poliza',
            name='renovacion_descartada',
            field=models.BooleanField(db_index=True, default=False, help_text='True si el operador marcó que el cliente no va a renovar.'),
        ),
        migrations.AddField(
            model_name='poliza',
            name='renovacion_descartada_detalle',
            field=models.TextField(blank=True, default='', help_text="Detalle adicional (texto libre cuando el motivo es 'Otro')."),
        ),
        migrations.AddField(
            model_name='poliza',
            name='renovacion_descartada_en',
            field=models.DateTimeField(blank=True, help_text='Cuándo se marcó como no-renueva.', null=True),
        ),
        migrations.AddField(
            model_name='poliza',
            name='renovacion_descartada_motivo',
            field=models.CharField(blank=True, choices=[('CAMBIO_COMPANIA', 'Cambió de compañía'), ('VENDIO_AUTO', 'Vendió el auto'), ('NO_QUIERE', 'No quiere seguir'), ('NO_CONTESTA', 'No contesta'), ('NO_PAGO', 'No pagó'), ('OTRO', 'Otro')], help_text='Motivo por el que no renueva.', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='poliza',
            name='renovacion_verificada',
            field=models.BooleanField(db_index=True, default=False, help_text='True si el operador marcó la póliza como verificada en la bandeja de renovaciones.'),
        ),
        migrations.AddField(
            model_name='poliza',
            name='renovacion_verificada_en',
            field=models.DateTimeField(blank=True, help_text='Cuándo se marcó como verificada.', null=True),
        ),
        migrations.DeleteModel(
            name='PolizaContactoRenovacion',
        ),
    ]
