# Generated by Django 5.2.7 on 2026-05-27 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polizas', '0020_poliza_renovacion_descartada_and_more'),
        ('usuarios', '0004_alter_perfil_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poliza',
            name='oficina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polizas_ficha', to='usuarios.oficina'),
        ),
    ]
