# Generated by Django 5.2.7 on 2026-05-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polizas', '0021_alter_poliza_oficina'),
    ]

    operations = [
        migrations.AddField(
            model_name='poliza',
            name='verificacion_compania',
            field=models.CharField(blank=True, choices=[('OK', 'Verificada en la compañía'), ('NO_FIGURA', 'No figura en la compañía')], db_index=True, default='', help_text='Resultado de la verificación manual contra el portal de la compañía.', max_length=10),
        ),
        migrations.AddField(
            model_name='poliza',
            name='verificacion_compania_en',
            field=models.DateTimeField(blank=True, help_text='Cuándo se marcó la verificación con la compañía.', null=True),
        ),
    ]
