# Generated by Django 5.2.7 on 2026-06-01 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polizas', '0022_poliza_verificacion_compania_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poliza',
            name='carroceria',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='poliza',
            name='combustible',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='poliza',
            name='numero_chasis',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='poliza',
            name='numero_motor',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='poliza',
            name='observaciones',
            field=models.TextField(blank=True, default=''),
        ),
    ]
