# Generated by Django 5.2.7 on 2026-06-19 05:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polizas', '0023_poliza_carroceria_poliza_combustible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poliza',
            name='creado_en',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
