# Generated by Django 5.2.7 on 2026-06-19 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polizas', '0024_poliza_creado_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='poliza',
            name='poliza_enviada',
            field=models.BooleanField(db_index=True, default=False, help_text='True si ya se le envió la póliza al cliente.'),
        ),
        migrations.AddField(
            model_name='poliza',
            name='poliza_enviada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
