# Generated by Django 5.2.7 on 2026-06-23 21:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polizas', '0026_token_portal_cupon_reportado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuponrobo',
            name='comprobante_public_id',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='cuponrobo',
            name='comprobante_url',
            field=models.TextField(blank=True, default='', help_text='Comprobante de pago que sube el cliente desde el portal (opcional).'),
        ),
        migrations.AlterField(
            model_name='cuponrobo',
            name='reportado_en',
            field=models.DateTimeField(blank=True, help_text="Cuándo el cliente tocó 'Ya pagué' en el link.", null=True),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='token_portal',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Token para el link público donde el cliente confirma pagos de cupones.', unique=True),
        ),
    ]
