# Generated by Django 5.2.7 on 2026-06-30 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polizas', '0027_cuponrobo_comprobante_public_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poliza',
            name='patente',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
