# Generated by Django 5.2.7 on 2026-07-21 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polizas', '0028_alter_poliza_patente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comision',
        ),
    ]
