# Generated by Django 5.2.7 on 2026-07-21 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polizas', '0029_delete_comision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poliza',
            name='poliza_enviada',
        ),
        migrations.RemoveField(
            model_name='poliza',
            name='poliza_enviada_en',
        ),
    ]
