# Generated by Django 5.2.7 on 2026-06-26 01:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0005_oficina_whatsapp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoPuntos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('puntos', models.IntegerField(help_text='Positivo suma, negativo resta.')),
                ('categoria', models.CharField(choices=[('control_diario', 'Control diario'), ('tarea_dia', 'Tarea del día'), ('venta', 'Venta / alta'), ('renovacion', 'Renovación'), ('pago', 'Cobro / pago'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('detalle', models.CharField(blank=True, default='', max_length=200)),
                ('ref', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('oficina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_puntos', to='usuarios.oficina')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_puntos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de puntos',
                'verbose_name_plural': 'Movimientos de puntos',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['fecha'], name='ranking_mov_fecha_c55972_idx'), models.Index(fields=['usuario', 'fecha'], name='ranking_mov_usuario_65c951_idx')],
            },
        ),
    ]
